from .battlescar import (
    BattleScarCreateView,
    BattleScarDetailView,
    BattleScarListView,
    BattleScarUpdateView,
)
from .camp import CampCreateView, CampDetailView, CampListView, CampUpdateView
from .charm import (
    SpiritCharmCreateView,
    SpiritCharmDetailView,
    SpiritCharmListView,
    SpiritCharmUpdateView,
)
from .drone import (
    DroneBasicsView,
    DroneCharacterCreationView,
    DroneDetailView,
    DroneUpdateView,
)
from .fera import (
    FeraBasicsView,
    FeraCharacterCreationView,
    FeraDetailView,
    FeraUpdateView,
)
from .fomor import (
    FomorAbilityView,
    FomorAttributeView,
    FomorBackgroundsView,
    FomorBasicsView,
    FomorCharacterCreationView,
    FomorCreateView,
    FomorDetailView,
    FomorExtrasView,
    FomorFreebiesView,
    FomorLanguagesView,
    FomorPowersView,
    FomorSpecialtiesView,
    FomorUpdateView,
)
from .fomoripower import (
    FomoriPowerCreateView,
    FomoriPowerDetailView,
    FomoriPowerListView,
    FomoriPowerUpdateView,
)
from .garou import (
    WerewolfBasicsView,
    WerewolfCharacterCreationView,
    WerewolfCreateView,
    WerewolfDetailView,
    WerewolfUpdateView,
)
from .gift import GiftCreateView, GiftDetailView, GiftListView, GiftUpdateView
from .kinfolk import (
    KinfolkBasicsView,
    KinfolkCharacterCreationView,
    KinfolkCreateView,
    KinfolkDetailView,
    KinfolkUpdateView,
)
from .pack import PackCreateView, PackDetailView, PackListView, PackUpdateView
from .renownincident import (
    RenownIncidentCreateView,
    RenownIncidentDetailView,
    RenownIncidentListView,
    RenownIncidentUpdateView,
)
from .rite import RiteCreateView, RiteDetailView, RiteListView, RiteUpdateView
from .septposition import (
    SeptPositionCreateView,
    SeptPositionDetailView,
    SeptPositionUpdateView,
)
from .spirit import SpiritCreateView, SpiritDetailView, SpiritUpdateView
from .totem import TotemCreateView, TotemDetailView, TotemListView, TotemUpdateView
from .tribe import TribeCreateView, TribeDetailView, TribeListView, TribeUpdateView
from .wtahuman import (
    WtAHumanBasicsView,
    WtAHumanCharacterCreationView,
    WtAHumanCreateView,
    WtAHumanDetailView,
    WtAHumanTemplateSelectView,
    WtAHumanUpdateView,
)

__all__ = [
    "BattleScarCreateView",
    "BattleScarDetailView",
    "BattleScarListView",
    "BattleScarUpdateView",
    "CampCreateView",
    "CampDetailView",
    "CampListView",
    "CampUpdateView",
    "SpiritCharmCreateView",
    "SpiritCharmDetailView",
    "SpiritCharmListView",
    "SpiritCharmUpdateView",
    "DroneBasicsView",
    "DroneCharacterCreationView",
    "DroneDetailView",
    "DroneUpdateView",
    "FeraBasicsView",
    "FeraCharacterCreationView",
    "FeraDetailView",
    "FeraUpdateView",
    "FomorAbilityView",
    "FomorAttributeView",
    "FomorBackgroundsView",
    "FomorBasicsView",
    "FomorCharacterCreationView",
    "FomorCreateView",
    "FomorDetailView",
    "FomorExtrasView",
    "FomorFreebiesView",
    "FomorLanguagesView",
    "FomorPowersView",
    "FomorSpecialtiesView",
    "FomorUpdateView",
    "FomoriPowerCreateView",
    "FomoriPowerDetailView",
    "FomoriPowerListView",
    "FomoriPowerUpdateView",
    "WerewolfBasicsView",
    "WerewolfCharacterCreationView",
    "WerewolfCreateView",
    "WerewolfDetailView",
    "WerewolfUpdateView",
    "GiftCreateView",
    "GiftDetailView",
    "GiftListView",
    "GiftUpdateView",
    "KinfolkBasicsView",
    "KinfolkCharacterCreationView",
    "KinfolkCreateView",
    "KinfolkDetailView",
    "KinfolkUpdateView",
    "PackCreateView",
    "PackDetailView",
    "PackListView",
    "PackUpdateView",
    "RenownIncidentCreateView",
    "RenownIncidentDetailView",
    "RenownIncidentListView",
    "RenownIncidentUpdateView",
    "RiteCreateView",
    "RiteDetailView",
    "RiteListView",
    "RiteUpdateView",
    "SeptPositionCreateView",
    "SeptPositionDetailView",
    "SeptPositionUpdateView",
    "SpiritCreateView",
    "SpiritDetailView",
    "SpiritUpdateView",
    "TotemCreateView",
    "TotemDetailView",
    "TotemListView",
    "TotemUpdateView",
    "TribeCreateView",
    "TribeDetailView",
    "TribeListView",
    "TribeUpdateView",
    "WtAHumanBasicsView",
    "WtAHumanCharacterCreationView",
    "WtAHumanCreateView",
    "WtAHumanDetailView",
    "WtAHumanTemplateSelectView",
    "WtAHumanUpdateView",
]
