"""Text normalization shared by scene posts and the scene chat consumer."""

_SINGLE_QUOTES = (
    0x2018,  # LEFT SINGLE QUOTATION MARK
    0x2019,  # RIGHT SINGLE QUOTATION MARK
    0x201A,  # SINGLE LOW-9 QUOTATION MARK
    0x201B,  # SINGLE HIGH-REVERSED-9 QUOTATION MARK
    0x2032,  # PRIME
    0x02B9,  # MODIFIER LETTER PRIME
    0x02BB,  # MODIFIER LETTER TURNED COMMA
    0x02BC,  # MODIFIER LETTER APOSTROPHE
    0x02BD,  # MODIFIER LETTER REVERSED COMMA
    0x275B,  # HEAVY SINGLE TURNED COMMA QUOTATION MARK ORNAMENT
    0x275C,  # HEAVY SINGLE COMMA QUOTATION MARK ORNAMENT
    0xFF07,  # FULLWIDTH APOSTROPHE
    0x00B4,  # ACUTE ACCENT
    0x0060,  # GRAVE ACCENT
)

_DOUBLE_QUOTES = (
    0x201C,  # LEFT DOUBLE QUOTATION MARK
    0x201D,  # RIGHT DOUBLE QUOTATION MARK
    0x201E,  # DOUBLE LOW-9 QUOTATION MARK
    0x201F,  # DOUBLE HIGH-REVERSED-9 QUOTATION MARK
    0x2033,  # DOUBLE PRIME
    0x02BA,  # MODIFIER LETTER DOUBLE PRIME
    0x275D,  # HEAVY DOUBLE TURNED COMMA QUOTATION MARK ORNAMENT
    0x275E,  # HEAVY DOUBLE COMMA QUOTATION MARK ORNAMENT
    0xFF02,  # FULLWIDTH QUOTATION MARK
)

_TRANSLATION = {
    **dict.fromkeys(_SINGLE_QUOTES, ord("'")),
    **dict.fromkeys(_DOUBLE_QUOTES, ord('"')),
}


def straighten_quotes(s):
    """Normalize typographic quotation marks and apostrophes to ASCII."""
    return s.translate(_TRANSLATION)
