"""One declaration per routable model. Custom workflows live in views/."""

from core.model_registry import ActionSpec, ModelRegistry, ModelSpec

registry = ModelRegistry(
    "items",
    [
        ModelSpec(
            model_label="items.MummyRelic",
            slug="mummy_relic",
            group="mummy",
            gameline="mtr",
            label="Mummy Relic",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mummy.MummyRelicDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("relic", "relic/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.mummy.MummyRelicListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("relic", "relic/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mummy.MummyRelicCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Relic '{name}' created successfully!",
                        "error_message": "Failed to create relic. Please correct the errors below.",
                    },
                    routes=[("relic", "relic/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.mummy.MummyRelicUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Relic '{name}' updated successfully!",
                        "error_message": "Failed to update relic. Please correct the errors below.",
                    },
                    routes=[("relic", "relic/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:mummy:relic",
                "update": "items:mummy:update:relic",
                "create": "items:mummy:create:relic",
                "list": "items:mummy:list:relic",
            },
            fields=(
                "name",
                "description",
                "rank",
                "relic_type",
                "era",
                "original_owner",
                "powers",
                "ba_cost",
                "associated_hekau",
                "requires_sekhem",
                "requires_ritual",
                "is_cursed",
                "is_unique",
                "is_sentient",
                "material",
                "hieroglyphic_inscription",
                "history",
                "current_location_notes",
            ),
            templates={
                "detail": "items/mummy/relic/detail.html",
                "list": "items/mummy/relic/list.html",
                "create": "items/mummy/relic/form.html",
                "update": "items/mummy/relic/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Vessel",
            slug="vessel",
            group="mummy",
            gameline="mtr",
            label="Vessel",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mummy.VesselDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("vessel", "vessel/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.mummy.VesselListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("vessel", "vessel/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mummy.VesselCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "rank",
                            "vessel_type",
                            "transfer_rate",
                            "efficiency",
                            "is_portable",
                            "requires_ritual",
                            "is_attuned",
                            "attuned_to",
                            "material",
                            "inscriptions",
                        ],
                        "success_message": "Vessel '{name}' created successfully!",
                        "error_message": "Failed to create vessel. Please correct the errors below.",
                    },
                    routes=[("vessel", "vessel/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.mummy.VesselUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "rank",
                            "current_ba",
                            "vessel_type",
                            "transfer_rate",
                            "efficiency",
                            "is_portable",
                            "requires_ritual",
                            "is_attuned",
                            "attuned_to",
                            "material",
                            "inscriptions",
                        ],
                        "success_message": "Vessel '{name}' updated successfully!",
                        "error_message": "Failed to update vessel. Please correct the errors below.",
                    },
                    routes=[("vessel", "vessel/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:mummy:vessel",
                "update": "items:mummy:update:vessel",
                "create": "items:mummy:create:vessel",
                "list": "items:mummy:list:vessel",
            },
            templates={
                "detail": "items/mummy/vessel/detail.html",
                "list": "items/mummy/vessel/list.html",
                "create": "items/mummy/vessel/form.html",
                "update": "items/mummy/vessel/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Ushabti",
            slug="ushabti",
            group="mummy",
            gameline="mtr",
            label="Ushabti",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mummy.UshabtiDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("ushabti", "ushabti/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.mummy.UshabtiListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("ushabti", "ushabti/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mummy.UshabtiCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "rank",
                            "purpose",
                            "physical_rating",
                            "mental_rating",
                            "special_abilities",
                            "material",
                            "size_description",
                            "appearance",
                            "command_word",
                            "obeys_only_creator",
                            "creator",
                        ],
                        "success_message": "Ushabti '{name}' created successfully!",
                        "error_message": "Failed to create ushabti. Please correct the errors below.",
                    },
                    routes=[("ushabti", "ushabti/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.mummy.UshabtiUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "rank",
                            "is_currently_animated",
                            "animation_duration_hours",
                            "purpose",
                            "physical_rating",
                            "mental_rating",
                            "special_abilities",
                            "material",
                            "size_description",
                            "appearance",
                            "command_word",
                            "obeys_only_creator",
                            "creator",
                        ],
                        "success_message": "Ushabti '{name}' updated successfully!",
                        "error_message": "Failed to update ushabti. Please correct the errors below.",
                    },
                    routes=[("ushabti", "ushabti/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:mummy:ushabti",
                "update": "items:mummy:update:ushabti",
                "create": "items:mummy:create:ushabti",
                "list": "items:mummy:list:ushabti",
            },
            templates={
                "detail": "items/mummy/ushabti/detail.html",
                "list": "items/mummy/ushabti/list.html",
                "create": "items/mummy/ushabti/form.html",
                "update": "items/mummy/ushabti/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Treasure",
            slug="treasure",
            group="changeling",
            gameline="ctd",
            label="Treasure",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.changeling.TreasureDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("treasure", "treasure/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.changeling.TreasureListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("treasure", "treasures/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.changeling.TreasureCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("treasure", "treasure/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.changeling.TreasureUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("treasure", "treasure/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:changeling:update:treasure",
                "create": "items:changeling:create:treasure",
                "list": "items:changeling:list:treasure",
            },
            fields=(
                "name",
                "description",
                "rating",
                "treasure_type",
                "creator",
                "creation_method",
                "permanence",
                "special_abilities",
                "glamour_storage",
                "glamour_affinity",
            ),
            templates={
                "detail": "items/changeling/treasure/detail.html",
                "list": "items/changeling/treasure/list.html",
                "create": "items/changeling/treasure/form.html",
                "update": "items/changeling/treasure/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Dross",
            slug="dross",
            group="changeling",
            gameline="ctd",
            label="Dross",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.changeling.DrossDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("dross", "dross/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.changeling.DrossListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("dross", "dross/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.changeling.DrossCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("dross", "dross/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.changeling.DrossUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("dross", "dross/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:changeling:dross",
                "update": "items:changeling:update:dross",
                "create": "items:changeling:create:dross",
                "list": "items:changeling:list:dross",
            },
            fields=(
                "name",
                "description",
                "quality",
                "glamour_value",
                "physical_form",
                "color",
                "source",
                "is_stable",
                "decay_rate",
                "resonance",
                "special_effects",
                "restricted_to",
                "is_consumable",
                "recharge_method",
                "container_description",
                "estimated_value",
            ),
            templates={
                "detail": "items/changeling/dross/detail.html",
                "list": "items/changeling/dross/list.html",
                "create": "items/changeling/dross/form.html",
                "update": "items/changeling/dross/form.html",
            },
        ),
        ModelSpec(
            model_label="items.ItemModel",
            slug="item",
            group="core",
            gameline="wod",
            label="Item",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.item.ItemDetailView",
                    policy="OBJECT_DETAIL",
                ),
                "list": ActionSpec(
                    view_path="items.views.core.item.ItemListView",
                    policy="OBJECT_LIST",
                    routes=[("item", "item/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.item.ItemCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": ["name", "description"],
                        "success_message": "Item '{name}' created successfully!",
                        "error_message": "Failed to create Item. Please correct the errors below.",
                    },
                    routes=[("item", "item/")],
                    custom="items.views.core.item._ItemCreateView",
                ),
                "update": ActionSpec(
                    view_path="items.views.core.item.ItemUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": ["name", "description"],
                        "success_message": "Item '{name}' updated successfully!",
                        "error_message": "Failed to update Item. Please correct the errors below.",
                    },
                    routes=[("item", "item/<int:pk>/")],
                    custom="items.views.core.item._ItemUpdateView",
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:update:item",
                "create": "items:create:item",
                "list": "items:list:item",
            },
            templates={
                "detail": "items/core/item/detail.html",
                "create": "items/core/item/form.html",
                "update": "items/core/item/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Material",
            slug="material",
            group="core",
            gameline="wod",
            label="Material",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.material.MaterialDetailView",
                    policy="PUBLIC_READ",
                    routes=[("material", "material/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.core.material.MaterialListView",
                    policy="PUBLIC_READ",
                    options={"ordering": ["name"]},
                    routes=[("material", "material/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.material.MaterialCreateView",
                    policy="STAFF_WRITE",
                    options={
                        "success_message": "Material '{name}' created successfully!",
                        "error_message": "Failed to create Material. Please correct the errors below.",
                    },
                    routes=[("material", "material/")],
                    form_updates={"name": {"attrs": {"placeholder": "Enter name here", "rows": 1}}},
                ),
                "update": ActionSpec(
                    view_path="items.views.core.material.MaterialUpdateView",
                    policy="STAFF_WRITE",
                    options={
                        "success_message": "Material '{name}' updated successfully!",
                        "error_message": "Failed to update Material. Please correct the errors below.",
                    },
                    routes=[("material", "material/<int:pk>/")],
                    form_updates={"name": {"attrs": {"placeholder": "Enter name here", "rows": 1}}},
                ),
            },
            model_urls={
                "detail": "items:material",
                "update": "items:update:material",
                "create": "items:create:material",
                "list": "items:list:material",
            },
            fields=("name", "is_hard"),
            templates={
                "detail": "items/core/material/detail.html",
                "list": "items/core/material/list.html",
                "create": "items/core/material/form.html",
                "update": "items/core/material/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Medium",
            slug="medium",
            group="core",
            gameline="wod",
            label="Medium",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.medium.MediumDetailView",
                    policy="PUBLIC_READ",
                    routes=[("medium", "medium/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.core.medium.MediumListView",
                    policy="PUBLIC_READ",
                    options={"ordering": ["name"]},
                    routes=[("medium", "medium/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.medium.MediumCreateView",
                    policy="STAFF_WRITE",
                    options={
                        "success_message": "Medium '{name}' created successfully!",
                        "error_message": "Failed to create Medium. Please correct the errors below.",
                    },
                    routes=[("medium", "medium/")],
                    form_updates={"name": {"attrs": {"placeholder": "Enter name here", "rows": 1}}},
                ),
                "update": ActionSpec(
                    view_path="items.views.core.medium.MediumUpdateView",
                    policy="STAFF_WRITE",
                    options={
                        "success_message": "Medium '{name}' updated successfully!",
                        "error_message": "Failed to update Medium. Please correct the errors below.",
                    },
                    routes=[("medium", "medium/<int:pk>/")],
                    form_updates={"name": {"attrs": {"placeholder": "Enter name here", "rows": 1}}},
                ),
            },
            model_urls={
                "detail": "items:medium",
                "update": "items:update:medium",
                "create": "items:create:medium",
                "list": "items:list:medium",
            },
            fields=("name", "length_modifier_type", "length_modifier"),
            templates={
                "detail": "items/core/medium/detail.html",
                "list": "items/core/medium/list.html",
                "create": "items/core/medium/form.html",
                "update": "items/core/medium/form.html",
            },
        ),
        ModelSpec(
            model_label="items.MeleeWeapon",
            slug="melee_weapon",
            group="core",
            gameline="wod",
            label="Melee Weapon",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.meleeweapon.MeleeWeaponDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("melee_weapon", "melee_weapon/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.core.meleeweapon.MeleeWeaponListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("melee_weapon", "melee_weapon/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.meleeweapon.MeleeWeaponCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Melee Weapon '{name}' created successfully!",
                        "error_message": "Failed to create Melee Weapon. Please correct the errors below.",
                    },
                    routes=[("melee_weapon", "meleeweapon/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.core.meleeweapon.MeleeWeaponUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Melee Weapon '{name}' updated successfully!",
                        "error_message": "Failed to update Melee Weapon. Please correct the errors below.",
                    },
                    routes=[("melee_weapon", "meleeweapon/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:update:melee_weapon",
                "create": "items:create:melee_weapon",
                "list": "items:list:melee_weapon",
            },
            fields=("name", "description", "difficulty", "damage", "damage_type", "conceal"),
            templates={
                "detail": "items/core/meleeweapon/detail.html",
                "list": "items/core/meleeweapon/list.html",
                "create": "items/core/meleeweapon/form.html",
                "update": "items/core/meleeweapon/form.html",
            },
        ),
        ModelSpec(
            model_label="items.RangedWeapon",
            slug="ranged_weapon",
            group="core",
            gameline="wod",
            label="Ranged Weapon",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.rangedweapon.RangedWeaponDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("ranged_weapon", "ranged_weapon/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.core.rangedweapon.RangedWeaponListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("ranged_weapon", "ranged_weapon/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.rangedweapon.RangedWeaponCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Ranged Weapon '{name}' created successfully!",
                        "error_message": "Failed to create Ranged Weapon. Please correct the errors below.",
                    },
                    routes=[("ranged_weapon", "rangedweapon/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.core.rangedweapon.RangedWeaponUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Ranged Weapon '{name}' updated successfully!",
                        "error_message": "Failed to update Ranged Weapon. Please correct the errors below.",
                    },
                    routes=[("ranged_weapon", "rangedweapon/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:update:ranged_weapon",
                "create": "items:create:ranged_weapon",
                "list": "items:list:ranged_weapon",
            },
            fields=(
                "name",
                "description",
                "difficulty",
                "damage",
                "damage_type",
                "conceal",
                "range",
                "rate",
                "clip",
            ),
            templates={
                "detail": "items/core/rangedweapon/detail.html",
                "list": "items/core/rangedweapon/list.html",
                "create": "items/core/rangedweapon/form.html",
                "update": "items/core/rangedweapon/form.html",
            },
        ),
        ModelSpec(
            model_label="items.ThrownWeapon",
            slug="thrown_weapon",
            group="core",
            gameline="wod",
            label="Thrown Weapon",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.thrownweapon.ThrownWeaponDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("thrown_weapon", "thrown_weapon/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.core.thrownweapon.ThrownWeaponListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("thrown_weapon", "thrown_weapon/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.thrownweapon.ThrownWeaponCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Thrown Weapon '{name}' created successfully!",
                        "error_message": "Failed to create Thrown Weapon. Please correct the errors below.",
                    },
                    routes=[("thrown_weapon", "thrownweapon/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.core.thrownweapon.ThrownWeaponUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Thrown Weapon '{name}' updated successfully!",
                        "error_message": "Failed to update Thrown Weapon. Please correct the errors below.",
                    },
                    routes=[("thrown_weapon", "thrownweapon/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:update:thrown_weapon",
                "create": "items:create:thrown_weapon",
                "list": "items:list:thrown_weapon",
            },
            fields=("name", "description", "difficulty", "damage", "damage_type", "conceal"),
            templates={
                "detail": "items/core/thrownweapon/detail.html",
                "list": "items/core/thrownweapon/list.html",
                "create": "items/core/thrownweapon/form.html",
                "update": "items/core/thrownweapon/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Weapon",
            slug="weapon",
            group="core",
            gameline="wod",
            label="Weapon",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.core.weapon.WeaponDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("weapon", "weapon/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.core.weapon.WeaponListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("weapon", "weapon/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.core.weapon.WeaponCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Weapon '{name}' created successfully!",
                        "error_message": "Failed to create Weapon. Please correct the errors below.",
                    },
                    routes=[("weapon", "weapon/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.core.weapon.WeaponUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Weapon '{name}' updated successfully!",
                        "error_message": "Failed to update Weapon. Please correct the errors below.",
                    },
                    routes=[("weapon", "weapon/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:update:weapon",
                "create": "items:create:weapon",
                "list": "items:list:weapon",
            },
            fields=("name", "description", "difficulty", "damage", "damage_type", "conceal"),
            templates={
                "detail": "items/core/weapon/detail.html",
                "list": "items/core/weapon/list.html",
                "create": "items/core/weapon/form.html",
                "update": "items/core/weapon/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Relic",
            slug="demon_relic",
            group="demon",
            gameline="dtf",
            label="Relic",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.demon.relic.RelicDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("relic", "relic/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.demon.relic.RelicListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("relic", "relics/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.demon.relic.RelicCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Relic '{name}' created successfully!",
                        "error_message": "Failed to create relic. Please correct the errors below.",
                    },
                    routes=[("relic", "relic/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.demon.relic.RelicUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Relic '{name}' updated successfully!",
                        "error_message": "Failed to update relic. Please correct the errors below.",
                    },
                    routes=[("relic", "relic/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:demon:relic",
                "update": "items:demon:update:relic",
                "create": "items:demon:create:relic",
                "list": "items:demon:list:relic",
            },
            fields=(
                "name",
                "description",
                "relic_type",
                "complexity",
                "lore_used",
                "power",
                "material",
                "house",
                "is_permanent",
                "difficulty",
                "dice_pool",
            ),
            templates={
                "detail": "items/demon/relic/detail.html",
                "list": "items/demon/relic/list.html",
                "create": "items/demon/relic/form.html",
                "update": "items/demon/relic/form.html",
            },
        ),
        ModelSpec(
            model_label="items.HunterGear",
            slug="hunter_gear",
            group="hunter",
            gameline="htr",
            label="Hunter Gear",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.hunter.gear.HunterGearDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("gear", "gear/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.hunter.gear.HunterGearListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("gear", "gear/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.hunter.gear.HunterGearCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Hunter Gear '{name}' created successfully!",
                        "error_message": "Failed to create gear. Please correct the errors below.",
                    },
                    routes=[("gear", "gear/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.hunter.gear.HunterGearUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Hunter Gear '{name}' updated successfully!",
                        "error_message": "Failed to update gear. Please correct the errors below.",
                    },
                    routes=[("gear", "gear/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:hunter:update:gear",
                "create": "items:hunter:create:gear",
                "list": "items:hunter:list:gear",
            },
            fields=(
                "name",
                "description",
                "gear_type",
                "damage",
                "range",
                "rate",
                "capacity",
                "concealability",
                "availability",
                "legality",
                "requires_training",
            ),
            templates={
                "detail": "items/hunter/gear/detail.html",
                "list": "items/hunter/gear/list.html",
                "create": "items/hunter/gear/form.html",
                "update": "items/hunter/gear/form.html",
            },
        ),
        ModelSpec(
            model_label="items.HunterRelic",
            slug="hunter_relic",
            group="hunter",
            gameline="htr",
            label="Hunter Relic",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.hunter.relic.HunterRelicDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("relic", "relic/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.hunter.relic.HunterRelicListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("relic", "relics/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.hunter.relic.HunterRelicCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Hunter Relic '{name}' created successfully!",
                        "error_message": "Failed to create relic. Please correct the errors below.",
                    },
                    routes=[("relic", "relic/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.hunter.relic.HunterRelicUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Hunter Relic '{name}' updated successfully!",
                        "error_message": "Failed to update relic. Please correct the errors below.",
                    },
                    routes=[("relic", "relic/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:hunter:update:relic",
                "create": "items:hunter:create:relic",
                "list": "items:hunter:list:relic",
            },
            fields=(
                "name",
                "description",
                "power_level",
                "background_cost",
                "is_blessed",
                "is_cursed",
                "requires_faith",
                "is_unique",
                "powers",
                "activation_cost",
                "origin",
                "limitations",
            ),
            templates={
                "detail": "items/hunter/relic/detail.html",
                "list": "items/hunter/relic/list.html",
                "create": "items/hunter/relic/form.html",
                "update": "items/hunter/relic/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Artifact",
            slug="artifact",
            group="mage",
            gameline="mta",
            label="Artifact",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.artifact.ArtifactDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("artifact", "artifact/<int:pk>/")],
                    custom="items.views.mage.artifact._ArtifactDetailView",
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.artifact.ArtifactListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("artifact", "artifact/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.artifact.ArtifactCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Artifact '{name}' created successfully!",
                        "error_message": "Failed to create Artifact. Please correct the errors below.",
                    },
                    routes=[("artifact", "artifact/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.artifact.ArtifactUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Artifact '{name}' updated successfully!",
                        "error_message": "Failed to update Artifact. Please correct the errors below.",
                    },
                    routes=[("artifact", "artifact/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:mage:update:artifact",
                "create": "items:mage:create:artifact",
                "list": "items:mage:list:artifact",
            },
            fields=("name", "rank", "background_cost", "quintessence_max", "description", "power"),
            templates={
                "detail": "items/mage/artifact/detail.html",
                "list": "items/mage/artifact/list.html",
                "create": "items/mage/artifact/form.html",
                "update": "items/mage/artifact/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Charm",
            slug="charm",
            group="mage",
            gameline="mta",
            label="Charm",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.charm.CharmDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("charm", "charm/<int:pk>/")],
                    custom="items.views.mage.charm._CharmDetailView",
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.charm.CharmListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("charm", "charm/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.charm.CharmCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Charm '{name}' created successfully!",
                        "error_message": "Failed to create Charm. Please correct the errors below.",
                    },
                    routes=[("charm", "charm/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.charm.CharmUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Charm '{name}' updated successfully!",
                        "error_message": "Failed to update Charm. Please correct the errors below.",
                    },
                    routes=[("charm", "charm/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:mage:update:charm",
                "create": "items:mage:create:charm",
                "list": "items:mage:list:charm",
            },
            fields=(
                "name",
                "rank",
                "background_cost",
                "quintessence_max",
                "description",
                "power",
                "arete",
            ),
            templates={
                "detail": "items/mage/charm/detail.html",
                "list": "items/mage/charm/list.html",
                "create": "items/mage/charm/form.html",
                "update": "items/mage/charm/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Grimoire",
            slug="grimoire",
            group="mage",
            gameline="mta",
            label="Grimoire",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.grimoire.GrimoireDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("grimoire", "grimoire/<int:pk>/")],
                    custom="items.views.mage.grimoire._GrimoireDetailView",
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.grimoire.GrimoireListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("grimoire", "grimoire/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.grimoire.GrimoireCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "rank",
                            "background_cost",
                            "description",
                            "abilities",
                            "spheres",
                            "date_written",
                            "faction",
                            "practices",
                            "instruments",
                            "is_primer",
                            "language",
                            "length",
                            "cover_material",
                            "inner_material",
                            "medium",
                            "rotes",
                        ],
                        "success_message": "Grimoire '{name}' created successfully!",
                        "error_message": "Failed to create Grimoire. Please correct the errors below.",
                    },
                    routes=[("grimoire", "grimoire/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.grimoire.GrimoireUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "rank",
                            "description",
                            "abilities",
                            "spheres",
                            "date_written",
                            "faction",
                            "practices",
                            "instruments",
                            "is_primer",
                            "language",
                            "length",
                            "cover_material",
                            "inner_material",
                            "medium",
                            "rotes",
                        ],
                        "success_message": "Grimoire '{name}' updated successfully!",
                        "error_message": "Failed to update Grimoire. Please correct the errors below.",
                    },
                    routes=[("grimoire", "grimoire/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:mage:update:grimoire",
                "create": "items:mage:create:grimoire",
                "list": "items:mage:list:grimoire",
            },
            templates={
                "detail": "items/mage/grimoire/detail.html",
                "list": "items/mage/grimoire/list.html",
                "create": "items/mage/grimoire/form.html",
                "update": "items/mage/grimoire/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Periapt",
            slug="periapt",
            group="mage",
            gameline="mta",
            label="Periapt",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.periapt.PeriaptDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("periapt", "periapt/<int:pk>/")],
                    custom="items.views.mage.periapt._PeriaptDetailView",
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.periapt.PeriaptListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("periapt", "periapt/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.periapt.PeriaptCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Periapt '{name}' created successfully!",
                        "error_message": "Failed to create Periapt. Please correct the errors below.",
                    },
                    routes=[("periapt", "periapt/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.periapt.PeriaptUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Periapt '{name}' updated successfully!",
                        "error_message": "Failed to update Periapt. Please correct the errors below.",
                    },
                    routes=[("periapt", "periapt/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:mage:update:periapt",
                "create": "items:mage:create:periapt",
                "list": "items:mage:list:periapt",
            },
            fields=(
                "name",
                "rank",
                "background_cost",
                "quintessence_max",
                "description",
                "power",
                "arete",
                "max_charges",
                "current_charges",
                "is_consumable",
            ),
            templates={
                "detail": "items/mage/periapt/detail.html",
                "list": "items/mage/periapt/list.html",
                "create": "items/mage/periapt/form.html",
                "update": "items/mage/periapt/form.html",
            },
        ),
        ModelSpec(
            model_label="items.SorcererArtifact",
            slug="sorcerer_artifact",
            group="mage",
            gameline="mta",
            label="Artifact (Sorcerer)",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.sorcerer_artifact.SorcererArtifactDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("sorcerer_artifact", "sorcerer_artifact/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.sorcerer_artifact.SorcererArtifactListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("sorcerer_artifact", "sorcerer_artifact/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.sorcerer_artifact.SorcererArtifactCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Sorcerer Artifact '{name}' created successfully!",
                        "error_message": "Failed to create Sorcerer Artifact. Please correct the errors below.",
                    },
                    routes=[("sorcerer_artifact", "sorcerer_artifact/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.sorcerer_artifact.SorcererArtifactUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Sorcerer Artifact '{name}' updated successfully!",
                        "error_message": "Failed to update Sorcerer Artifact. Please correct the errors below.",
                    },
                    routes=[("sorcerer_artifact", "sorcerer_artifact/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:update:item",
                "create": "items:create:item",
                "list": "items:mage:list:sorcerer_artifact",
            },
            fields=("name", "rank", "background_cost", "description", "power"),
            templates={
                "detail": "items/mage/sorcerer_artifact/detail.html",
                "list": "items/mage/sorcerer_artifact/list.html",
                "create": "items/mage/sorcerer_artifact/form.html",
                "update": "items/mage/sorcerer_artifact/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Talisman",
            slug="talisman",
            group="mage",
            gameline="mta",
            label="Talisman",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.talisman.TalismanDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("talisman", "talisman/<int:pk>/")],
                    custom="items.views.mage.talisman._TalismanDetailView",
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.talisman.TalismanListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("talisman", "talisman/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.talisman.TalismanCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Talisman '{name}' created successfully!",
                        "error_message": "Failed to create Talisman. Please correct the errors below.",
                    },
                    routes=[("talisman", "talisman/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.talisman.TalismanUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Talisman '{name}' updated successfully!",
                        "error_message": "Failed to update Talisman. Please correct the errors below.",
                    },
                    routes=[("talisman", "talisman/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:mage:update:talisman",
                "create": "items:mage:create:talisman",
                "list": "items:mage:list:talisman",
            },
            fields=(
                "name",
                "rank",
                "background_cost",
                "quintessence_max",
                "description",
                "powers",
                "arete",
            ),
            templates={
                "detail": "items/mage/talisman/detail.html",
                "list": "items/mage/talisman/list.html",
                "create": "items/mage/talisman/form.html",
                "update": "items/mage/talisman/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Wonder",
            slug="wonder",
            group="mage",
            gameline="mta",
            label="Wonder",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.mage.wonder.WonderDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("wonder", "wonder/<int:pk>/")],
                    custom="items.views.mage.wonder._WonderDetailView",
                ),
                "list": ActionSpec(
                    view_path="items.views.mage.wonder.WonderListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("wonder", "wonder/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.mage.wonder.WonderCreateView",
                    policy="OBJECT_CREATE",
                    custom="items.views.mage.wonder._WonderCreateView",
                    options={
                        "success_message": "Wonder '{name}' created successfully!",
                        "error_message": "Failed to create wonder. Please correct the errors below.",
                    },
                    routes=[("wonder", "wonder/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.mage.wonder.WonderUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Wonder '{name}' updated successfully!",
                        "error_message": "Failed to update wonder. Please correct the errors below.",
                    },
                    routes=[("wonder", "wonder/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:mage:update:wonder",
                "create": "items:mage:create:wonder",
                "list": "items:mage:list:wonder",
            },
            form_class="items.forms.mage.wonder.WonderForm",
            templates={
                "detail": "items/mage/wonder/detail.html",
                "list": "items/mage/wonder/list.html",
                "create": "items/mage/wonder/form.html",
                "update": "items/mage/wonder/form.html",
            },
        ),
        ModelSpec(
            model_label="items.VampireArtifact",
            slug="vampire_artifact",
            group="vampire",
            gameline="vtm",
            label="Vampire Artifact",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.vampire.VampireArtifactDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("artifact", "artifact/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.vampire.VampireArtifactListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("artifact", "artifacts/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.vampire.VampireArtifactCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Vampire Artifact '{name}' created successfully!",
                        "error_message": "Failed to create Vampire Artifact. Please correct the errors below.",
                    },
                    routes=[("artifact", "artifact/")],
                    custom="items.views.vampire._VampireArtifactCreateView",
                ),
                "update": ActionSpec(
                    view_path="items.views.vampire.VampireArtifactUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Vampire Artifact '{name}' updated successfully!",
                        "error_message": "Failed to update Vampire Artifact. Please correct the errors below.",
                    },
                    routes=[("artifact", "artifact/<int:pk>/")],
                    custom="items.views.vampire._VampireArtifactUpdateView",
                ),
            },
            model_urls={
                "detail": "items:vampire:artifact",
                "update": "items:vampire:update:artifact",
                "create": "items:vampire:create:artifact",
                "list": "items:vampire:list:artifact",
            },
            form_class="items.forms.vampire.artifact.VampireArtifactForm",
            templates={
                "detail": "items/vampire/artifact/detail.html",
                "list": "items/vampire/artifact/list.html",
                "create": "items/vampire/artifact/form.html",
                "update": "items/vampire/artifact/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Bloodstone",
            slug="bloodstone",
            group="vampire",
            gameline="vtm",
            label="Bloodstone",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.vampire.BloodstoneDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("bloodstone", "bloodstone/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.vampire.BloodstoneListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("bloodstone", "bloodstones/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.vampire.BloodstoneCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("bloodstone", "bloodstone/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.vampire.BloodstoneUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("bloodstone", "bloodstone/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:vampire:update:bloodstone",
                "create": "items:vampire:create:bloodstone",
                "list": "items:vampire:list:bloodstone",
            },
            fields=(
                "name",
                "description",
                "blood_stored",
                "max_blood",
                "is_active",
                "created_by_generation",
                "stone_type",
            ),
            templates={
                "detail": "items/vampire/bloodstone/detail.html",
                "list": "items/vampire/bloodstone/list.html",
                "create": "items/vampire/bloodstone/form.html",
                "update": "items/vampire/bloodstone/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Fetish",
            slug="fetish",
            group="werewolf",
            gameline="wta",
            label="Fetish",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.werewolf.fetish.FetishDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("fetish", "fetish/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.werewolf.fetish.FetishListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("fetish", "fetish/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.werewolf.fetish.FetishCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Fetish '{name}' created successfully!",
                        "error_message": "Failed to create fetish. Please correct the errors below.",
                    },
                    routes=[("fetish", "fetish/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.werewolf.fetish.FetishUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Fetish '{name}' updated successfully!",
                        "error_message": "Failed to update fetish. Please correct the errors below.",
                    },
                    routes=[("fetish", "fetish/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:werewolf:update:fetish",
                "create": "items:werewolf:create:fetish",
                "list": "items:werewolf:list:fetish",
            },
            fields=(
                "name",
                "rank",
                "background_cost",
                "quintessence_max",
                "description",
                "gnosis",
                "spirit",
            ),
            templates={
                "detail": "items/werewolf/fetish/detail.html",
                "list": "items/werewolf/fetish/list.html",
                "create": "items/werewolf/fetish/form.html",
                "update": "items/werewolf/fetish/form.html",
            },
        ),
        ModelSpec(
            model_label="items.Talen",
            slug="talen",
            group="werewolf",
            gameline="wta",
            label="Talen",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.werewolf.talen.TalenDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("talen", "talen/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.werewolf.talen.TalenListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("talen", "talen/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.werewolf.talen.TalenCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Talen '{name}' created successfully!",
                        "error_message": "Failed to create Talen. Please correct the errors below.",
                    },
                    routes=[("talen", "talen/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
                "update": ActionSpec(
                    view_path="items.views.werewolf.talen.TalenUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Talen '{name}' updated successfully!",
                        "error_message": "Failed to update Talen. Please correct the errors below.",
                    },
                    routes=[("talen", "talen/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "items:item",
                "update": "items:werewolf:update:talen",
                "create": "items:werewolf:create:talen",
                "list": "items:werewolf:list:talen",
            },
            fields=(
                "name",
                "rank",
                "background_cost",
                "quintessence_max",
                "description",
                "gnosis",
                "spirit",
            ),
            templates={
                "detail": "items/werewolf/talen/detail.html",
                "list": "items/werewolf/talen/list.html",
                "create": "items/werewolf/talen/form.html",
                "update": "items/werewolf/talen/form.html",
            },
        ),
        ModelSpec(
            model_label="items.WraithRelic",
            slug="wraith_relic",
            group="wraith",
            gameline="wto",
            label="Relic",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.wraith.WraithRelicDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("relic", "relic/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.wraith.WraithRelicListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("relic", "relics/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.wraith.WraithRelicCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("relic", "relic/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.wraith.WraithRelicUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("relic", "relic/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:wraith:relic",
                "update": "items:wraith:update:relic",
                "create": "items:wraith:create:relic",
                "list": "items:wraith:list:relic",
            },
            fields=("name", "description", "level", "rarity", "pathos_cost"),
            templates={
                "detail": "items/wraith/relic/detail.html",
                "list": "items/wraith/relic/list.html",
                "create": "items/wraith/relic/form.html",
                "update": "items/wraith/relic/form.html",
            },
        ),
        ModelSpec(
            model_label="items.WraithArtifact",
            slug="wraith_artifact",
            group="wraith",
            gameline="wto",
            label="Artifact",
            actions={
                "detail": ActionSpec(
                    view_path="items.views.wraith.WraithArtifactDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("artifact", "artifact/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="items.views.wraith.WraithArtifactListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("artifact", "artifacts/")],
                ),
                "create": ActionSpec(
                    view_path="items.views.wraith.WraithArtifactCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("artifact", "artifact/")],
                ),
                "update": ActionSpec(
                    view_path="items.views.wraith.WraithArtifactUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("artifact", "artifact/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "items:wraith:artifact",
                "update": "items:wraith:update:artifact",
                "create": "items:wraith:create:artifact",
                "list": "items:wraith:list:artifact",
            },
            fields=(
                "name",
                "description",
                "level",
                "artifact_type",
                "material",
                "corpus",
                "pathos_cost",
            ),
            templates={
                "detail": "items/wraith/artifact/detail.html",
                "list": "items/wraith/artifact/list.html",
                "create": "items/wraith/artifact/form.html",
                "update": "items/wraith/artifact/form.html",
            },
        ),
    ],
)
