"""Explicit, reviewed route policies. Missing entries deny in production."""

POLICIES = {
    'ACCOUNT': frozenset("""
accounts.views.FreebieAwardView
accounts.views.ImageApprovalView
accounts.views.MarkSceneReadView
accounts.views.ObjectApprovalView
accounts.views.ObjectRevisionView
accounts.views.ObjectSubmissionView
accounts.views.ProfileUpdateView
accounts.views.ProfileView
accounts.views.SceneXPAwardView
accounts.views.WeeklyXPApprovalView
accounts.views.WeeklyXPRequestView
    """.split()),
    'CHARGEN_STEP': frozenset("""
characters.views.changeling.changeling.ChangelingAbilityView
characters.views.changeling.changeling.ChangelingAlliesView
characters.views.changeling.changeling.ChangelingArtsRealmsView
characters.views.changeling.changeling.ChangelingAttributeView
characters.views.changeling.changeling.ChangelingBackgroundsView
characters.views.changeling.changeling.ChangelingExtrasView
characters.views.changeling.changeling.ChangelingFreebiesView
characters.views.changeling.changeling.ChangelingLanguagesView
characters.views.changeling.changeling.ChangelingSpecialtiesView
characters.views.changeling.ctdhuman.CtDHumanAbilityView
characters.views.changeling.ctdhuman.CtDHumanAlliesView
characters.views.changeling.ctdhuman.CtDHumanAttributeView
characters.views.changeling.ctdhuman.CtDHumanBackgroundsView
characters.views.changeling.ctdhuman.CtDHumanExtrasView
characters.views.changeling.ctdhuman.CtDHumanFreebiesView
characters.views.changeling.ctdhuman.CtDHumanLanguagesView
characters.views.changeling.ctdhuman.CtDHumanSpecialtiesView
characters.views.core.human.HumanAbilityChargenView
characters.views.core.human.HumanAttributeChargenView
characters.views.core.human.HumanBackgroundsChargenView
characters.views.core.human.HumanBiographicalInformationChargenView
characters.views.core.human.HumanFreebiesChargenView
characters.views.core.human.HumanLanguagesChargenView
characters.views.core.human.HumanSpecialtiesChargenView
characters.views.demon.demon_chargen.DemonAbilityView
characters.views.demon.demon_chargen.DemonAlliesView
characters.views.demon.demon_chargen.DemonApocalypticFormView
characters.views.demon.demon_chargen.DemonAttributeView
characters.views.demon.demon_chargen.DemonBackgroundsView
characters.views.demon.demon_chargen.DemonContactsView
characters.views.demon.demon_chargen.DemonExtrasView
characters.views.demon.demon_chargen.DemonFollowersView
characters.views.demon.demon_chargen.DemonFreebiesView
characters.views.demon.demon_chargen.DemonLanguagesView
characters.views.demon.demon_chargen.DemonLoresView
characters.views.demon.demon_chargen.DemonMentorView
characters.views.demon.demon_chargen.DemonRetainersView
characters.views.demon.demon_chargen.DemonSpecialtiesView
characters.views.demon.demon_chargen.DemonVirtuesView
characters.views.demon.dtfhuman_chargen.DtFHumanAbilityView
characters.views.demon.dtfhuman_chargen.DtFHumanAlliesView
characters.views.demon.dtfhuman_chargen.DtFHumanAttributeView
characters.views.demon.dtfhuman_chargen.DtFHumanBackgroundsView
characters.views.demon.dtfhuman_chargen.DtFHumanExtrasView
characters.views.demon.dtfhuman_chargen.DtFHumanFreebiesView
characters.views.demon.dtfhuman_chargen.DtFHumanLanguagesView
characters.views.demon.dtfhuman_chargen.DtFHumanSpecialtiesView
characters.views.demon.thrall_chargen.ThrallAbilityView
characters.views.demon.thrall_chargen.ThrallAlliesView
characters.views.demon.thrall_chargen.ThrallAttributeView
characters.views.demon.thrall_chargen.ThrallBackgroundsView
characters.views.demon.thrall_chargen.ThrallExtrasView
characters.views.demon.thrall_chargen.ThrallFreebiesView
characters.views.demon.thrall_chargen.ThrallLanguagesView
characters.views.demon.thrall_chargen.ThrallSpecialtiesView
characters.views.demon.thrall_chargen.ThrallVirtuesView
characters.views.mage.companion.CompanionAbilityView
characters.views.mage.companion.CompanionAlliesView
characters.views.mage.companion.CompanionAttributeView
characters.views.mage.companion.CompanionBackgroundsView
characters.views.mage.companion.CompanionChantryView
characters.views.mage.companion.CompanionEnhancementView
characters.views.mage.companion.CompanionExtrasView
characters.views.mage.companion.CompanionFreebiesView
characters.views.mage.companion.CompanionLanguagesView
characters.views.mage.companion.CompanionLibraryView
characters.views.mage.companion.CompanionNodeView
characters.views.mage.companion.CompanionSanctumView
characters.views.mage.companion.CompanionSpecialtiesView
characters.views.mage.companion.CompanionWonderView
characters.views.mage.mage.MageAbilityView
characters.views.mage.mage.MageAlliesView
characters.views.mage.mage.MageAttributeView
characters.views.mage.mage.MageBackgroundsView
characters.views.mage.mage.MageChantryView
characters.views.mage.mage.MageContactsView
characters.views.mage.mage.MageEnhancementView
characters.views.mage.mage.MageExtrasView
characters.views.mage.mage.MageFamiliarView
characters.views.mage.mage.MageFocusView
characters.views.mage.mage.MageFreebiesView
characters.views.mage.mage.MageLanguagesView
characters.views.mage.mage.MageLibraryView
characters.views.mage.mage.MageMentorView
characters.views.mage.mage.MageNodeView
characters.views.mage.mage.MageRetainersView
characters.views.mage.mage.MageRoteView
characters.views.mage.mage.MageSanctumView
characters.views.mage.mage.MageSpecialtiesView
characters.views.mage.mage.MageSpheresView
characters.views.mage.mage.MageWonderView
characters.views.mage.mtahuman.MtAHumanAbilityView
characters.views.mage.mtahuman.MtAHumanAlliesView
characters.views.mage.mtahuman.MtAHumanAttributeView
characters.views.mage.mtahuman.MtAHumanBackgroundsView
characters.views.mage.mtahuman.MtAHumanChantryView
characters.views.mage.mtahuman.MtAHumanEnhancementView
characters.views.mage.mtahuman.MtAHumanExtrasView
characters.views.mage.mtahuman.MtAHumanFreebiesView
characters.views.mage.mtahuman.MtAHumanLanguagesView
characters.views.mage.mtahuman.MtAHumanLibraryView
characters.views.mage.mtahuman.MtAHumanNodeView
characters.views.mage.mtahuman.MtAHumanSanctumView
characters.views.mage.mtahuman.MtAHumanSpecialtiesView
characters.views.mage.mtahuman.MtAHumanWonderView
characters.views.mage.sorcerer.SorcererAbilityView
characters.views.mage.sorcerer.SorcererAlliesView
characters.views.mage.sorcerer.SorcererArtifactView
characters.views.mage.sorcerer.SorcererAttributeView
characters.views.mage.sorcerer.SorcererBackgroundsView
characters.views.mage.sorcerer.SorcererChantryView
characters.views.mage.sorcerer.SorcererEnhancementView
characters.views.mage.sorcerer.SorcererExtrasView
characters.views.mage.sorcerer.SorcererFamiliarView
characters.views.mage.sorcerer.SorcererFreebiesView
characters.views.mage.sorcerer.SorcererLanguagesView
characters.views.mage.sorcerer.SorcererLibraryView
characters.views.mage.sorcerer.SorcererNodeView
characters.views.mage.sorcerer.SorcererPathView
characters.views.mage.sorcerer.SorcererPsychicView
characters.views.mage.sorcerer.SorcererRitualView
characters.views.mage.sorcerer.SorcererSanctumView
characters.views.mage.sorcerer.SorcererSpecialtiesView
characters.views.vampire.ghoul_chargen.GhoulAbilityView
characters.views.vampire.ghoul_chargen.GhoulAlliesView
characters.views.vampire.ghoul_chargen.GhoulAttributeView
characters.views.vampire.ghoul_chargen.GhoulBackgroundsView
characters.views.vampire.ghoul_chargen.GhoulDisciplinesView
characters.views.vampire.ghoul_chargen.GhoulExtrasView
characters.views.vampire.ghoul_chargen.GhoulFreebiesView
characters.views.vampire.ghoul_chargen.GhoulLanguagesView
characters.views.vampire.ghoul_chargen.GhoulSpecialtiesView
characters.views.vampire.vampire_chargen.VampireAbilityView
characters.views.vampire.vampire_chargen.VampireAlliesView
characters.views.vampire.vampire_chargen.VampireAttributeView
characters.views.vampire.vampire_chargen.VampireBackgroundsView
characters.views.vampire.vampire_chargen.VampireContactsView
characters.views.vampire.vampire_chargen.VampireDisciplinesView
characters.views.vampire.vampire_chargen.VampireExtrasView
characters.views.vampire.vampire_chargen.VampireFreebiesView
characters.views.vampire.vampire_chargen.VampireLanguagesView
characters.views.vampire.vampire_chargen.VampireMentorView
characters.views.vampire.vampire_chargen.VampireRetainersView
characters.views.vampire.vampire_chargen.VampireSpecialtiesView
characters.views.vampire.vampire_chargen.VampireVirtuesView
characters.views.vampire.vtmhuman.VtMHumanAbilityView
characters.views.vampire.vtmhuman.VtMHumanAlliesView
characters.views.vampire.vtmhuman.VtMHumanAttributeView
characters.views.vampire.vtmhuman.VtMHumanBackgroundsView
characters.views.vampire.vtmhuman.VtMHumanExtrasView
characters.views.vampire.vtmhuman.VtMHumanFreebiesView
characters.views.vampire.vtmhuman.VtMHumanLanguagesView
characters.views.vampire.vtmhuman.VtMHumanSpecialtiesView
characters.views.werewolf.drone.DroneAbilityView
characters.views.werewolf.drone.DroneAttributeView
characters.views.werewolf.drone.DroneBackgroundsView
characters.views.werewolf.drone.DroneExtrasView
characters.views.werewolf.drone.DroneFreebiesView
characters.views.werewolf.drone.DroneLanguagesView
characters.views.werewolf.drone.DroneSpecialtiesView
characters.views.werewolf.fera.FeraAbilityView
characters.views.werewolf.fera.FeraAlliesView
characters.views.werewolf.fera.FeraAttributeView
characters.views.werewolf.fera.FeraBackgroundsView
characters.views.werewolf.fera.FeraBreedFactionView
characters.views.werewolf.fera.FeraExtrasView
characters.views.werewolf.fera.FeraFreebiesView
characters.views.werewolf.fera.FeraGiftsView
characters.views.werewolf.fera.FeraHistoryView
characters.views.werewolf.fera.FeraLanguagesView
characters.views.werewolf.fera.FeraSpecialtiesView
characters.views.werewolf.fomor.FomorAbilityView
characters.views.werewolf.fomor.FomorAlliesView
characters.views.werewolf.fomor.FomorAttributeView
characters.views.werewolf.fomor.FomorBackgroundsView
characters.views.werewolf.fomor.FomorContactsView
characters.views.werewolf.fomor.FomorExtrasView
characters.views.werewolf.fomor.FomorFreebiesView
characters.views.werewolf.fomor.FomorLanguagesView
characters.views.werewolf.fomor.FomorPowersView
characters.views.werewolf.fomor.FomorSpecialtiesView
characters.views.werewolf.garou.WerewolfAbilityView
characters.views.werewolf.garou.WerewolfAlliesView
characters.views.werewolf.garou.WerewolfAttributeView
characters.views.werewolf.garou.WerewolfBackgroundsView
characters.views.werewolf.garou.WerewolfContactsView
characters.views.werewolf.garou.WerewolfExtrasView
characters.views.werewolf.garou.WerewolfFreebiesView
characters.views.werewolf.garou.WerewolfGiftsView
characters.views.werewolf.garou.WerewolfHistoryView
characters.views.werewolf.garou.WerewolfLanguagesView
characters.views.werewolf.garou.WerewolfMentorView
characters.views.werewolf.garou.WerewolfSpecialtiesView
characters.views.werewolf.kinfolk.KinfolkAbilityView
characters.views.werewolf.kinfolk.KinfolkAlliesView
characters.views.werewolf.kinfolk.KinfolkAttributeView
characters.views.werewolf.kinfolk.KinfolkBackgroundsView
characters.views.werewolf.kinfolk.KinfolkExtrasView
characters.views.werewolf.kinfolk.KinfolkFreebiesView
characters.views.werewolf.kinfolk.KinfolkLanguagesView
characters.views.werewolf.kinfolk.KinfolkSpecialtiesView
characters.views.werewolf.wtahuman.WtAHumanAbilityView
characters.views.werewolf.wtahuman.WtAHumanAlliesView
characters.views.werewolf.wtahuman.WtAHumanAttributeView
characters.views.werewolf.wtahuman.WtAHumanBackgroundsView
characters.views.werewolf.wtahuman.WtAHumanExtrasView
characters.views.werewolf.wtahuman.WtAHumanFreebiesView
characters.views.werewolf.wtahuman.WtAHumanLanguagesView
characters.views.werewolf.wtahuman.WtAHumanSpecialtiesView
characters.views.wraith.wraith_chargen.WraithAbilityView
characters.views.wraith.wraith_chargen.WraithAlliesView
characters.views.wraith.wraith_chargen.WraithArcanosView
characters.views.wraith.wraith_chargen.WraithAttributeView
characters.views.wraith.wraith_chargen.WraithBackgroundsView
characters.views.wraith.wraith_chargen.WraithContactsView
characters.views.wraith.wraith_chargen.WraithExtrasView
characters.views.wraith.wraith_chargen.WraithFettersView
characters.views.wraith.wraith_chargen.WraithFreebiesView
characters.views.wraith.wraith_chargen.WraithLanguagesView
characters.views.wraith.wraith_chargen.WraithMentorView
characters.views.wraith.wraith_chargen.WraithPassionsView
characters.views.wraith.wraith_chargen.WraithShadowView
characters.views.wraith.wraith_chargen.WraithSpecialtiesView
characters.views.wraith.wtohuman.WtOHumanAbilityView
characters.views.wraith.wtohuman.WtOHumanAlliesView
characters.views.wraith.wtohuman.WtOHumanAttributeView
characters.views.wraith.wtohuman.WtOHumanBackgroundsView
characters.views.wraith.wtohuman.WtOHumanExtrasView
characters.views.wraith.wtohuman.WtOHumanFreebiesView
characters.views.wraith.wtohuman.WtOHumanLanguagesView
characters.views.wraith.wtohuman.WtOHumanSpecialtiesView
locations.views.changeling.creation.FreeholdDetailsView
locations.views.changeling.creation.FreeholdFeaturesView
locations.views.changeling.creation.FreeholdPowersView
    """.split()),
    'GAME': frozenset("""
game.views.ChronicleCreateView
game.views.ChronicleDetailView
game.views.ChronicleListView
game.views.ChronicleUpdateView
game.views.CommandsView
game.views.FreebieSpendingRecordCreateView
game.views.FreebieSpendingRecordDetailView
game.views.FreebieSpendingRecordListView
game.views.FreebieSpendingRecordUpdateView
game.views.JournalDetailView
game.views.JournalListView
game.views.SceneCreateView
game.views.SceneDetailView
game.views.SceneListView
game.views.SceneUpdateView
game.views.SettingElementCreateView
game.views.SettingElementDetailView
game.views.SettingElementListView
game.views.SettingElementUpdateView
game.views.StoryCreateView
game.views.StoryDetailView
game.views.StoryListView
game.views.StoryUpdateView
game.views.StoryXPRequestCreateView
game.views.StoryXPRequestDetailView
game.views.StoryXPRequestListView
game.views.StoryXPRequestUpdateView
game.views.WeekCreateView
game.views.WeekDetailView
game.views.WeekListView
game.views.WeekUpdateView
game.views.WeeklyXPRequestApproveView
game.views.WeeklyXPRequestBatchApproveView
game.views.WeeklyXPRequestCreateView
game.views.WeeklyXPRequestDetailView
game.views.WeeklyXPRequestListView
game.views.XPSpendingRequestApproveView
game.views.XPSpendingRequestCreateView
game.views.XPSpendingRequestDetailView
game.views.XPSpendingRequestListView
game.views.XPSpendingRequestUpdateView
    """.split()),
    'LOGIN': frozenset("""
characters.views.changeling.changeling.ChangelingBasicsView
characters.views.changeling.ctdhuman.CtDHumanBasicsView
characters.views.changeling.ctdhuman.CtDHumanTemplateSelectView
characters.views.core.chargen_back.ChargenBackView
characters.views.core.npc.NPCProfileCreateView
characters.views.demon.demon_chargen.DemonBasicsView
characters.views.demon.dtfhuman_chargen.DtFHumanBasicsView
characters.views.demon.dtfhuman_chargen.DtFHumanTemplateSelectView
characters.views.demon.thrall_chargen.ThrallBasicsView
characters.views.mage.mage.MageBasicsView
characters.views.mage.mtahuman.MtAHumanBasicsView
characters.views.mage.mtahuman.MtAHumanTemplateSelectView
characters.views.vampire.ghoul_chargen.GhoulBasicsView
characters.views.vampire.vampire_chargen.VampireBasicsView
characters.views.vampire.vtmhuman.VtMHumanBasicsView
characters.views.vampire.vtmhuman.VtMHumanTemplateSelectView
characters.views.werewolf.drone.DroneBasicsView
characters.views.werewolf.fera.FeraBasicsView
characters.views.werewolf.fomor.FomorBasicsView
characters.views.werewolf.garou.WerewolfBasicsView
characters.views.werewolf.kinfolk.KinfolkBasicsView
characters.views.werewolf.wtahuman.WtAHumanBasicsView
characters.views.werewolf.wtahuman.WtAHumanTemplateSelectView
characters.views.wraith.wraith_chargen.WraithBasicsView
characters.views.wraith.wtohuman.WtOHumanBasicsView
characters.views.wraith.wtohuman.WtOHumanTemplateSelectView
core.views.character_template.CharacterTemplateImportView
core.views.character_template.CharacterTemplateQuickNPCView
items.views.mage.wonder.WonderCreateView
locations.views.changeling.freehold.FreeholdCreateView
locations.views.mage.chantry.LoadExamplesView
locations.views.mage.demesne.DemesneCreateView
locations.views.mage.library.LibraryCreateView
locations.views.mage.node.NodeCreateView
locations.views.mage.paradox_realm.ParadoxRealmCreateView
locations.views.mage.sanctum.SanctumCreateView
    """.split()),
    'OBJECT_ACTION': frozenset("""
locations.views.mage.paradox_realm.ParadoxRealmUpdateView
    """.split()),
    'OBJECT_CREATE': frozenset("""
characters.views.changeling.autumn_person.AutumnPersonCreateView
characters.views.changeling.chimera.ChimeraCreateView
characters.views.changeling.inanimae.InanimaeCreateView
characters.views.changeling.motley.MotleyCreateView
characters.views.changeling.nunnehi.NunnehiCreateView
characters.views.core.character.CharacterCreateView
characters.views.core.group.GroupCreateView
characters.views.core.human.HumanBasicsView
characters.views.core.human.HumanCreateView
characters.views.demon.conclave.ConclaveCreateView
characters.views.demon.earthbound.EarthboundCreateView
characters.views.hunter.htrhuman.HtRHumanCreateView
characters.views.hunter.hunter.HunterCreateView
characters.views.mage.cabal.CabalCreateView
characters.views.mage.effect.EffectCreateView
characters.views.mage.companion.CompanionBasicsView
characters.views.mage.companion.CompanionCreateView
characters.views.mage.mage.MageCreateView
characters.views.mage.rote.RoteCreateView
characters.views.mage.sorcerer.SorcererBasicsView
characters.views.mummy.mtr_human.MtRHumanCreateView
characters.views.mummy.mummy.MummyCreateView
characters.views.vampire.coterie.CoterieCreateView
characters.views.vampire.revenant.RevenantCreateView
characters.views.werewolf.pack.PackCreateView
characters.views.werewolf.spirit.SpiritCreateView
characters.views.wraith.circle.CircleCreateView
core.views.character_template.CharacterTemplateCreateView
items.views.changeling.DrossCreateView
items.views.changeling.TreasureCreateView
items.views.core.item.ItemCreateView
items.views.core.meleeweapon.MeleeWeaponCreateView
items.views.core.rangedweapon.RangedWeaponCreateView
items.views.core.thrownweapon.ThrownWeaponCreateView
items.views.core.weapon.WeaponCreateView
items.views.demon.relic.RelicCreateView
items.views.hunter.gear.HunterGearCreateView
items.views.hunter.relic.HunterRelicCreateView
items.views.mage.artifact.ArtifactCreateView
items.views.mage.charm.CharmCreateView
items.views.mage.grimoire.GrimoireCreateView
items.views.mage.periapt.PeriaptCreateView
items.views.mage.sorcerer_artifact.SorcererArtifactCreateView
items.views.mage.talisman.TalismanCreateView
items.views.mummy.MummyRelicCreateView
items.views.mummy.UshabtiCreateView
items.views.mummy.VesselCreateView
items.views.vampire.BloodstoneCreateView
items.views.vampire.VampireArtifactCreateView
items.views.werewolf.fetish.FetishCreateView
items.views.werewolf.talen.TalenCreateView
items.views.wraith.WraithArtifactCreateView
items.views.wraith.WraithRelicCreateView
locations.views.changeling.creation.FreeholdBasicsView
locations.views.changeling.dream_realm.DreamRealmCreateView
locations.views.changeling.holding.HoldingCreateView
locations.views.changeling.trod.TrodCreateView
locations.views.core.city.CityCreateView
locations.views.core.location.LocationCreateView
locations.views.demon.bastion.BastionCreateView
locations.views.demon.reliquary.ReliquaryCreateView
locations.views.hunter.huntingground.HuntingGroundCreateView
locations.views.hunter.safehouse.SafehouseCreateView
locations.views.mage.chantry.ChantryCreateView
locations.views.mage.realm.RealmCreateView
locations.views.mage.sector.SectorCreateView
locations.views.mummy.CultTempleCreateView
locations.views.mummy.TombCreateView
locations.views.mummy.UndergroundSanctuaryCreateView
locations.views.vampire.BarrensCreateView
locations.views.vampire.DomainCreateView
locations.views.vampire.ElysiumCreateView
locations.views.vampire.HavenCreateView
locations.views.vampire.RackCreateView
locations.views.vampire.TremereChantryCreateView
locations.views.werewolf.caern.CaernCreateView
locations.views.wraith.byway.BywayCreateView
locations.views.wraith.citadel.CitadelCreateView
locations.views.wraith.freehold.WraithFreeholdCreateView
locations.views.wraith.haunt.HauntCreateView
locations.views.wraith.necropolis.NecropolisCreateView
locations.views.wraith.nihil.NihilCreateView
    """.split()),
    'OBJECT_DETAIL': frozenset("""
characters.views.changeling.autumn_person.AutumnPersonDetailView
characters.views.changeling.chimera.ChimeraDetailView
characters.views.changeling.changeling.ChangelingDetailView
characters.views.changeling.ctdhuman.CtDHumanDetailView
characters.views.changeling.inanimae.InanimaeDetailView
characters.views.changeling.motley.MotleyDetailView
characters.views.changeling.nunnehi.NunnehiDetailView
characters.views.core.group.GroupDetailView
characters.views.core.human.HumanDetailView
characters.views.demon.conclave.ConclaveDetailView
characters.views.demon.demon.DemonDetailView
characters.views.demon.dtfhuman.DtFHumanDetailView
characters.views.demon.earthbound.EarthboundDetailView
characters.views.demon.thrall.ThrallDetailView
characters.views.hunter.htrhuman.HtRHumanDetailView
characters.views.hunter.hunter.HunterDetailView
characters.views.mage.cabal.CabalDetailView
characters.views.mage.effect.EffectDetailView
characters.views.mage.companion.CompanionDetailView
characters.views.mage.mage.MageDetailView
characters.views.mage.rote.RoteDetailView
characters.views.mage.mtahuman.MtAHumanDetailView
characters.views.mage.sorcerer.SorcererDetailView
characters.views.mummy.mtr_human.MtRHumanDetailView
characters.views.mummy.mummy.MummyDetailView
characters.views.vampire.coterie.CoterieDetailView
characters.views.vampire.ghoul.GhoulDetailView
characters.views.vampire.revenant.RevenantDetailView
characters.views.vampire.vampire.VampireDetailView
characters.views.vampire.vtmhuman.VtMHumanDetailView
characters.views.werewolf.drone.DroneDetailView
characters.views.werewolf.fera.FeraDetailView
characters.views.werewolf.fomor.FomorDetailView
characters.views.werewolf.garou.WerewolfDetailView
characters.views.werewolf.kinfolk.KinfolkDetailView
characters.views.werewolf.pack.PackDetailView
characters.views.werewolf.spirit.SpiritDetailView
characters.views.werewolf.wtahuman.WtAHumanDetailView
characters.views.wraith.circle.CircleDetailView
characters.views.wraith.wraith.WraithDetailView
characters.views.wraith.wtohuman.WtOHumanDetailView
core.views.character_template.CharacterTemplateDetailView
core.views.character_template.CharacterTemplateExportView
items.views.changeling.DrossDetailView
items.views.changeling.TreasureDetailView
items.views.core.item.ItemDetailView
items.views.core.meleeweapon.MeleeWeaponDetailView
items.views.core.rangedweapon.RangedWeaponDetailView
items.views.core.thrownweapon.ThrownWeaponDetailView
items.views.core.weapon.WeaponDetailView
items.views.demon.relic.RelicDetailView
items.views.hunter.gear.HunterGearDetailView
items.views.hunter.relic.HunterRelicDetailView
items.views.mage.artifact.ArtifactDetailView
items.views.mage.charm.CharmDetailView
items.views.mage.grimoire.GrimoireDetailView
items.views.mage.periapt.PeriaptDetailView
items.views.mage.sorcerer_artifact.SorcererArtifactDetailView
items.views.mage.talisman.TalismanDetailView
items.views.mage.wonder.WonderDetailView
items.views.mummy.MummyRelicDetailView
items.views.mummy.UshabtiDetailView
items.views.mummy.VesselDetailView
items.views.vampire.BloodstoneDetailView
items.views.vampire.VampireArtifactDetailView
items.views.werewolf.fetish.FetishDetailView
items.views.werewolf.talen.TalenDetailView
items.views.wraith.WraithArtifactDetailView
items.views.wraith.WraithRelicDetailView
locations.views.changeling.dream_realm.DreamRealmDetailView
locations.views.changeling.freehold.FreeholdDetailView
locations.views.changeling.holding.HoldingDetailView
locations.views.changeling.trod.TrodDetailView
locations.views.core.city.CityDetailView
locations.views.core.location.LocationDetailView
locations.views.demon.bastion.BastionDetailView
locations.views.demon.reliquary.ReliquaryDetailView
locations.views.hunter.huntingground.HuntingGroundDetailView
locations.views.hunter.safehouse.SafehouseDetailView
locations.views.mage.chantry.ChantryDetailView
locations.views.mage.demesne.DemesneDetailView
locations.views.mage.library.LibraryDetailView
locations.views.mage.node.NodeDetailView
locations.views.mage.paradox_realm.ParadoxRealmDetailView
locations.views.mage.realm.RealmDetailView
locations.views.mage.sanctum.SanctumDetailView
locations.views.mage.sector.SectorDetailView
locations.views.mummy.CultTempleDetailView
locations.views.mummy.TombDetailView
locations.views.mummy.UndergroundSanctuaryDetailView
locations.views.vampire.BarrensDetailView
locations.views.vampire.DomainDetailView
locations.views.vampire.ElysiumDetailView
locations.views.vampire.HavenDetailView
locations.views.vampire.RackDetailView
locations.views.vampire.TremereChantryDetailView
locations.views.werewolf.caern.CaernDetailView
locations.views.wraith.byway.BywayDetailView
locations.views.wraith.citadel.CitadelDetailView
locations.views.wraith.freehold.WraithFreeholdDetailView
locations.views.wraith.haunt.HauntDetailView
locations.views.wraith.necropolis.NecropolisDetailView
locations.views.wraith.nihil.NihilDetailView
    """.split()),
    'OBJECT_LIST': frozenset("""
characters.views.changeling.motley.MotleyListView
characters.views.changeling.chimera.ChimeraListView
characters.views.core.DeceasedCharacterIndex
characters.views.core.NPCCharacterIndex
characters.views.core.RetiredCharacterIndex
characters.views.demon.conclave.ConclaveListView
characters.views.demon.demon.DemonListView
characters.views.demon.dtfhuman.DtFHumanListView
characters.views.demon.earthbound.EarthboundListView
characters.views.demon.thrall.ThrallListView
characters.views.hunter.htrhuman.HtRHumanListView
characters.views.hunter.hunter.HunterListView
characters.views.mage.cabal.CabalListView
characters.views.mage.effect.EffectListView
characters.views.mage.rote.RoteListView
characters.views.mummy.mtr_human.MtRHumanListView
characters.views.mummy.mummy.MummyListView
characters.views.vampire.coterie.CoterieListView
characters.views.werewolf.pack.PackListView
characters.views.wraith.circle.CircleListView
core.views.character_template.CharacterTemplateListView
items.views.changeling.DrossListView
items.views.changeling.TreasureListView
items.views.core.meleeweapon.MeleeWeaponListView
items.views.core.rangedweapon.RangedWeaponListView
items.views.core.thrownweapon.ThrownWeaponListView
items.views.core.weapon.WeaponListView
items.views.demon.relic.RelicListView
items.views.hunter.gear.HunterGearListView
items.views.hunter.relic.HunterRelicListView
items.views.mage.artifact.ArtifactListView
items.views.mage.charm.CharmListView
items.views.mage.grimoire.GrimoireListView
items.views.mage.periapt.PeriaptListView
items.views.mage.sorcerer_artifact.SorcererArtifactListView
items.views.mage.talisman.TalismanListView
items.views.mage.wonder.WonderListView
items.views.mummy.MummyRelicListView
items.views.mummy.UshabtiListView
items.views.mummy.VesselListView
items.views.vampire.BloodstoneListView
items.views.vampire.VampireArtifactListView
items.views.werewolf.fetish.FetishListView
items.views.werewolf.talen.TalenListView
items.views.wraith.WraithArtifactListView
items.views.wraith.WraithRelicListView
locations.views.changeling.dream_realm.DreamRealmListView
locations.views.changeling.freehold.FreeholdListView
locations.views.changeling.holding.HoldingListView
locations.views.changeling.trod.TrodListView
locations.views.core.city.CityListView
locations.views.demon.bastion.BastionListView
locations.views.demon.reliquary.ReliquaryListView
locations.views.hunter.huntingground.HuntingGroundListView
locations.views.hunter.safehouse.SafehouseListView
locations.views.mage.chantry.ChantryListView
locations.views.mage.demesne.DemesneListView
locations.views.mage.library.LibraryListView
locations.views.mage.node.NodeListView
locations.views.mage.paradox_realm.ParadoxRealmListView
locations.views.mage.realm.RealmListView
locations.views.mage.sanctum.SanctumListView
locations.views.mage.sector.SectorListView
locations.views.mummy.CultTempleListView
locations.views.mummy.TombListView
locations.views.mummy.UndergroundSanctuaryListView
locations.views.vampire.BarrensListView
locations.views.vampire.DomainListView
locations.views.vampire.ElysiumListView
locations.views.vampire.HavenListView
locations.views.vampire.RackListView
locations.views.vampire.TremereChantryListView
locations.views.werewolf.caern.CaernListView
locations.views.wraith.byway.BywayListView
locations.views.wraith.citadel.CitadelListView
locations.views.wraith.freehold.WraithFreeholdListView
locations.views.wraith.haunt.HauntListView
locations.views.wraith.necropolis.NecropolisListView
locations.views.wraith.nihil.NihilListView
    """.split()),
    'OBJECT_WRITE': frozenset("""
characters.views.changeling.autumn_person.AutumnPersonUpdateView
characters.views.changeling.chimera.ChimeraUpdateView
characters.views.changeling.changeling.ChangelingUpdateView
characters.views.changeling.ctdhuman.CtDHumanUpdateView
characters.views.changeling.inanimae.InanimaeUpdateView
characters.views.changeling.motley.MotleyUpdateView
characters.views.changeling.nunnehi.NunnehiUpdateView
characters.views.core.character.CharacterUpdateView
characters.views.core.group.GroupUpdateView
characters.views.core.human.HumanUpdateView
characters.views.demon.conclave.ConclaveUpdateView
characters.views.demon.demon.DemonUpdateView
characters.views.demon.dtfhuman.DtFHumanUpdateView
characters.views.demon.earthbound.EarthboundUpdateView
characters.views.demon.thrall.ThrallUpdateView
characters.views.hunter.htrhuman.HtRHumanUpdateView
characters.views.hunter.hunter.HunterUpdateView
characters.views.mage.cabal.CabalUpdateView
characters.views.mage.effect.EffectUpdateView
characters.views.mage.companion.CompanionUpdateView
characters.views.mage.mage.MageUpdateView
characters.views.mage.rote.RoteUpdateView
characters.views.mage.mtahuman.MtAHumanUpdateView
characters.views.mage.sorcerer.SorcererUpdateView
characters.views.mummy.mtr_human.MtRHumanUpdateView
characters.views.mummy.mummy.MummyUpdateView
characters.views.vampire.coterie.CoterieUpdateView
characters.views.vampire.ghoul.GhoulUpdateView
characters.views.vampire.revenant.RevenantUpdateView
characters.views.vampire.vampire.VampireUpdateView
characters.views.vampire.vtmhuman.VtMHumanUpdateView
characters.views.werewolf.drone.DroneUpdateView
characters.views.werewolf.fera.FeraUpdateView
characters.views.werewolf.fomor.FomorUpdateView
characters.views.werewolf.garou.WerewolfUpdateView
characters.views.werewolf.kinfolk.KinfolkUpdateView
characters.views.werewolf.pack.PackUpdateView
characters.views.werewolf.spirit.SpiritUpdateView
characters.views.werewolf.wtahuman.WtAHumanUpdateView
characters.views.wraith.circle.CircleUpdateView
characters.views.wraith.wraith.WraithUpdateView
characters.views.wraith.wtohuman.WtOHumanUpdateView
core.views.character_template.CharacterTemplateDeleteView
core.views.character_template.CharacterTemplateUpdateView
items.views.changeling.DrossUpdateView
items.views.changeling.TreasureUpdateView
items.views.core.item.ItemUpdateView
items.views.core.meleeweapon.MeleeWeaponUpdateView
items.views.core.rangedweapon.RangedWeaponUpdateView
items.views.core.thrownweapon.ThrownWeaponUpdateView
items.views.core.weapon.WeaponUpdateView
items.views.demon.relic.RelicUpdateView
items.views.hunter.gear.HunterGearUpdateView
items.views.hunter.relic.HunterRelicUpdateView
items.views.mage.artifact.ArtifactUpdateView
items.views.mage.charm.CharmUpdateView
items.views.mage.grimoire.GrimoireUpdateView
items.views.mage.periapt.PeriaptUpdateView
items.views.mage.sorcerer_artifact.SorcererArtifactUpdateView
items.views.mage.talisman.TalismanUpdateView
items.views.mage.wonder.WonderUpdateView
items.views.mummy.MummyRelicUpdateView
items.views.mummy.UshabtiUpdateView
items.views.mummy.VesselUpdateView
items.views.vampire.BloodstoneUpdateView
items.views.vampire.VampireArtifactUpdateView
items.views.werewolf.fetish.FetishUpdateView
items.views.werewolf.talen.TalenUpdateView
items.views.wraith.WraithArtifactUpdateView
items.views.wraith.WraithRelicUpdateView
locations.views.changeling.dream_realm.DreamRealmUpdateView
locations.views.changeling.freehold.FreeholdUpdateView
locations.views.changeling.holding.HoldingUpdateView
locations.views.changeling.trod.TrodUpdateView
locations.views.core.city.CityUpdateView
locations.views.core.location.LocationUpdateView
locations.views.demon.bastion.BastionUpdateView
locations.views.demon.reliquary.ReliquaryUpdateView
locations.views.hunter.huntingground.HuntingGroundUpdateView
locations.views.hunter.safehouse.SafehouseUpdateView
locations.views.mage.chantry.ChantryUpdateView
locations.views.mage.demesne.DemesneUpdateView
locations.views.mage.library.LibraryUpdateView
locations.views.mage.node.NodeUpdateView
locations.views.mage.realm.RealmUpdateView
locations.views.mage.sanctum.SanctumUpdateView
locations.views.mage.sector.SectorUpdateView
locations.views.mummy.CultTempleUpdateView
locations.views.mummy.TombUpdateView
locations.views.mummy.UndergroundSanctuaryUpdateView
locations.views.vampire.BarrensUpdateView
locations.views.vampire.DomainUpdateView
locations.views.vampire.ElysiumUpdateView
locations.views.vampire.HavenUpdateView
locations.views.vampire.RackUpdateView
locations.views.vampire.TremereChantryUpdateView
locations.views.werewolf.caern.CaernUpdateView
locations.views.wraith.byway.BywayUpdateView
locations.views.wraith.citadel.CitadelUpdateView
locations.views.wraith.freehold.WraithFreeholdUpdateView
locations.views.wraith.haunt.HauntUpdateView
locations.views.wraith.necropolis.NecropolisUpdateView
locations.views.wraith.nihil.NihilUpdateView
    """.split()),
    'PUBLIC_CARD': frozenset("""
core.views.public_object.PublicObjectDetailView
    """.split()),
    'PUBLIC_INDEX': frozenset("""
characters.views.core.CharacterIndexView
items.views.core.ItemIndexView
locations.views.core.LocationIndexView
    """.split()),
    'PUBLIC_READ': frozenset("""
accounts.views.CustomLoginView
accounts.views.CustomPasswordResetView
accounts.views.SignUp
characters.views.changeling.cantrip.CantripDetailView
characters.views.changeling.cantrip.CantripListView
characters.views.changeling.house.HouseDetailView
characters.views.changeling.house.HouseListView
characters.views.changeling.house_faction.HouseFactionDetailView
characters.views.changeling.house_faction.HouseFactionListView
characters.views.changeling.kith.KithDetailView
characters.views.changeling.kith.KithListView
characters.views.changeling.legacy.LegacyDetailView
characters.views.changeling.legacy.LegacyListView
characters.views.core.archetype.ArchetypeDetailView
characters.views.core.archetype.ArchetypeListView
characters.views.core.derangement.DerangementDetailView
characters.views.core.derangement.DerangementListView
characters.views.core.meritflaw.MeritFlawDetailView
characters.views.core.meritflaw.MeritFlawListView
characters.views.core.specialty.SpecialtyDetailView
characters.views.core.specialty.SpecialtyListView
characters.views.demon.apocalyptic_trait.ApocalypticFormTraitDetailView
characters.views.demon.apocalyptic_trait.ApocalypticFormTraitListView
characters.views.demon.faction.DemonFactionDetailView
characters.views.demon.faction.DemonFactionListView
characters.views.demon.house.DemonHouseDetailView
characters.views.demon.house.DemonHouseListView
characters.views.demon.lore.LoreDetailView
characters.views.demon.lore.LoreListView
characters.views.demon.pact.PactDetailView
characters.views.demon.pact.PactListView
characters.views.demon.ritual.RitualDetailView
characters.views.demon.ritual.RitualListView
characters.views.demon.visage.VisageDetailView
characters.views.demon.visage.VisageListView
characters.views.hunter.creed.CreedDetailView
characters.views.hunter.creed.CreedListView
characters.views.hunter.edge.EdgeDetailView
characters.views.hunter.edge.EdgeListView
characters.views.hunter.organization.HunterOrganizationDetailView
characters.views.hunter.organization.HunterOrganizationListView
characters.views.mage.advantage.AdvantageDetailView
characters.views.mage.faction.MageFactionDetailView
characters.views.mage.faction.MageFactionListView
characters.views.mage.fellowship.SorcererFellowshipDetailView
characters.views.mage.fellowship.SorcererFellowshipListView
characters.views.mage.focus.CorruptedPracticeDetailView
characters.views.mage.focus.CorruptedPracticeListView
characters.views.mage.focus.InstrumentDetailView
characters.views.mage.focus.InstrumentListView
characters.views.mage.focus.ParadigmDetailView
characters.views.mage.focus.ParadigmListView
characters.views.mage.focus.PracticeDetailView
characters.views.mage.focus.PracticeListView
characters.views.mage.focus.SpecializedPracticeDetailView
characters.views.mage.focus.SpecializedPracticeListView
characters.views.mage.focus.TenetDetailView
characters.views.mage.focus.TenetListView
characters.views.mage.hedge_magic.PathDetailView
characters.views.mage.hedge_magic.PathListView
characters.views.mage.hedge_magic.RitualDetailView
characters.views.mage.hedge_magic.RitualListView
characters.views.mage.resonance.ResonanceDetailView
characters.views.mage.resonance.ResonanceListView
characters.views.mage.sphere.SphereDetailView
characters.views.mage.sphere.SphereListView
characters.views.mummy.dynasty.DynastyDetailView
characters.views.mummy.dynasty.DynastyListView
characters.views.mummy.mummy_title.MummyTitleDetailView
characters.views.mummy.mummy_title.MummyTitleListView
characters.views.vampire.clan.VampireClanDetailView
characters.views.vampire.clan.VampireClanListView
characters.views.vampire.discipline.DisciplineDetailView
characters.views.vampire.discipline.DisciplineListView
characters.views.vampire.path.PathDetailView
characters.views.vampire.path.PathListView
characters.views.vampire.revenant_family.RevenantFamilyDetailView
characters.views.vampire.revenant_family.RevenantFamilyListView
characters.views.vampire.sect.VampireSectDetailView
characters.views.vampire.sect.VampireSectListView
characters.views.vampire.title.VampireTitleDetailView
characters.views.vampire.title.VampireTitleListView
characters.views.werewolf.battlescar.BattleScarDetailView
characters.views.werewolf.battlescar.BattleScarListView
characters.views.werewolf.camp.CampDetailView
characters.views.werewolf.camp.CampListView
characters.views.werewolf.charm.SpiritCharmDetailView
characters.views.werewolf.charm.SpiritCharmListView
characters.views.werewolf.fomoripower.FomoriPowerDetailView
characters.views.werewolf.fomoripower.FomoriPowerListView
characters.views.werewolf.gift.GiftDetailView
characters.views.werewolf.gift.GiftListView
characters.views.werewolf.renownincident.RenownIncidentDetailView
characters.views.werewolf.renownincident.RenownIncidentListView
characters.views.werewolf.rite.RiteDetailView
characters.views.werewolf.rite.RiteListView
characters.views.werewolf.septposition.SeptPositionDetailView
characters.views.werewolf.totem.TotemDetailView
characters.views.werewolf.totem.TotemListView
characters.views.werewolf.tribe.TribeDetailView
characters.views.werewolf.tribe.TribeListView
characters.views.wraith.arcanos.ArcanosDetailView
characters.views.wraith.arcanos.ArcanosListView
characters.views.wraith.faction.WraithFactionDetailView
characters.views.wraith.faction.WraithFactionListView
characters.views.wraith.guild.GuildDetailView
characters.views.wraith.guild.GuildListView
characters.views.wraith.shadow_archetype.ShadowArchetypeDetailView
characters.views.wraith.shadow_archetype.ShadowArchetypeListView
characters.views.wraith.thorn.ThornDetailView
characters.views.wraith.thorn.ThornListView
core.views.book.BookDetailView
core.views.book.BookListView
core.views.home.HomeListView
core.views.houserules.HouseRuleDetailView
core.views.houserules.HouseRulesIndexView
core.views.language.LanguageDetailView
core.views.language.LanguageListView
core.views.newsitem.NewsItemDetailView
core.views.newsitem.NewsItemListView
items.views.core.material.MaterialDetailView
items.views.core.material.MaterialListView
items.views.core.medium.MediumDetailView
items.views.core.medium.MediumListView
locations.views.mage.reality_zone.RealityZoneDetailView
locations.views.mage.reality_zone.RealityZoneListView
    """.split()),
    'ROUTER': frozenset("""
characters.views.changeling.changeling.ChangelingCharacterCreationView
characters.views.changeling.ctdhuman.CtDHumanCharacterCreationView
characters.views.core.GenericCharacterDetailView
characters.views.core.GenericGroupDetailView
characters.views.core.human.HumanCharacterCreationView
characters.views.demon.demon_chargen.DemonCharacterCreationView
characters.views.demon.dtfhuman_chargen.DtFHumanCharacterCreationView
characters.views.demon.thrall_chargen.ThrallCharacterCreationView
characters.views.mage.companion.CopanionCharacterCreationView
characters.views.mage.focus.GenericPracticeDetailView
characters.views.mage.mage.MageCharacterCreationView
characters.views.mage.mtahuman.MtAHumanCharacterCreationView
characters.views.mage.sorcerer.SorcererCharacterCreationView
characters.views.vampire.ghoul_chargen.GhoulCharacterCreationView
characters.views.vampire.vampire_chargen.VampireCharacterCreationView
characters.views.vampire.vtmhuman.VtMHumanCharacterCreationView
characters.views.werewolf.drone.DroneCharacterCreationView
characters.views.werewolf.fera.FeraCharacterCreationView
characters.views.werewolf.fomor.FomorCharacterCreationView
characters.views.werewolf.garou.WerewolfCharacterCreationView
characters.views.werewolf.kinfolk.KinfolkCharacterCreationView
characters.views.werewolf.wtahuman.WtAHumanCharacterCreationView
characters.views.wraith.wraith_chargen.WraithCharacterCreationView
characters.views.wraith.wtohuman.WtOHumanCharacterCreationView
items.views.core.GenericItemDetailView
locations.views.changeling.creation.FreeholdCreationView
locations.views.core.GenericLocationDetailView
    """.split()),
    'STAFF_WRITE': frozenset("""
characters.views.changeling.cantrip.CantripCreateView
characters.views.changeling.cantrip.CantripUpdateView
characters.views.changeling.house.HouseCreateView
characters.views.changeling.house.HouseUpdateView
characters.views.changeling.house_faction.HouseFactionCreateView
characters.views.changeling.house_faction.HouseFactionUpdateView
characters.views.changeling.kith.KithCreateView
characters.views.changeling.kith.KithUpdateView
characters.views.changeling.legacy.LegacyCreateView
characters.views.changeling.legacy.LegacyUpdateView
characters.views.core.archetype.ArchetypeCreateView
characters.views.core.archetype.ArchetypeUpdateView
characters.views.core.derangement.DerangementCreateView
characters.views.core.derangement.DerangementUpdateView
characters.views.core.meritflaw.MeritFlawCreateView
characters.views.core.meritflaw.MeritFlawUpdateView
characters.views.core.specialty.SpecialtyCreateView
characters.views.core.specialty.SpecialtyUpdateView
characters.views.demon.apocalyptic_trait.ApocalypticFormTraitCreateView
characters.views.demon.apocalyptic_trait.ApocalypticFormTraitUpdateView
characters.views.demon.faction.DemonFactionCreateView
characters.views.demon.faction.DemonFactionUpdateView
characters.views.demon.house.DemonHouseCreateView
characters.views.demon.house.DemonHouseUpdateView
characters.views.demon.lore.LoreCreateView
characters.views.demon.lore.LoreUpdateView
characters.views.demon.pact.PactCreateView
characters.views.demon.pact.PactUpdateView
characters.views.demon.ritual.RitualUpdateView
characters.views.demon.visage.VisageCreateView
characters.views.demon.visage.VisageUpdateView
characters.views.hunter.creed.CreedCreateView
characters.views.hunter.creed.CreedUpdateView
characters.views.hunter.edge.EdgeCreateView
characters.views.hunter.edge.EdgeUpdateView
characters.views.hunter.organization.HunterOrganizationCreateView
characters.views.hunter.organization.HunterOrganizationUpdateView
characters.views.mage.faction.MageFactionCreateView
characters.views.mage.faction.MageFactionUpdateView
characters.views.mage.fellowship.SorcererFellowshipCreateView
characters.views.mage.fellowship.SorcererFellowshipUpdateView
characters.views.mage.focus.CorruptedPracticeCreateView
characters.views.mage.focus.CorruptedPracticeUpdateView
characters.views.mage.focus.InstrumentCreateView
characters.views.mage.focus.InstrumentUpdateView
characters.views.mage.focus.ParadigmCreateView
characters.views.mage.focus.ParadigmUpdateView
characters.views.mage.focus.PracticeCreateView
characters.views.mage.focus.PracticeUpdateView
characters.views.mage.focus.SpecializedPracticeCreateView
characters.views.mage.focus.SpecializedPracticeUpdateView
characters.views.mage.focus.TenetCreateView
characters.views.mage.focus.TenetUpdateView
characters.views.mage.hedge_magic.PathCreateView
characters.views.mage.hedge_magic.PathUpdateView
characters.views.mage.hedge_magic.RitualCreateView
characters.views.mage.hedge_magic.RitualUpdateView
characters.views.mage.resonance.ResonanceCreateView
characters.views.mage.resonance.ResonanceUpdateView
characters.views.mage.sphere.SphereCreateView
characters.views.mage.sphere.SphereUpdateView
characters.views.mummy.dynasty.DynastyCreateView
characters.views.mummy.dynasty.DynastyUpdateView
characters.views.mummy.mummy_title.MummyTitleCreateView
characters.views.mummy.mummy_title.MummyTitleUpdateView
characters.views.vampire.clan.VampireClanCreateView
characters.views.vampire.clan.VampireClanUpdateView
characters.views.vampire.discipline.DisciplineCreateView
characters.views.vampire.discipline.DisciplineUpdateView
characters.views.vampire.path.PathCreateView
characters.views.vampire.path.PathUpdateView
characters.views.vampire.revenant_family.RevenantFamilyCreateView
characters.views.vampire.revenant_family.RevenantFamilyUpdateView
characters.views.vampire.sect.VampireSectCreateView
characters.views.vampire.sect.VampireSectUpdateView
characters.views.vampire.title.VampireTitleCreateView
characters.views.vampire.title.VampireTitleUpdateView
characters.views.werewolf.battlescar.BattleScarCreateView
characters.views.werewolf.battlescar.BattleScarUpdateView
characters.views.werewolf.camp.CampCreateView
characters.views.werewolf.camp.CampUpdateView
characters.views.werewolf.charm.SpiritCharmCreateView
characters.views.werewolf.charm.SpiritCharmUpdateView
characters.views.werewolf.fomoripower.FomoriPowerCreateView
characters.views.werewolf.fomoripower.FomoriPowerUpdateView
characters.views.werewolf.gift.GiftCreateView
characters.views.werewolf.gift.GiftUpdateView
characters.views.werewolf.renownincident.RenownIncidentCreateView
characters.views.werewolf.renownincident.RenownIncidentUpdateView
characters.views.werewolf.rite.RiteCreateView
characters.views.werewolf.rite.RiteUpdateView
characters.views.werewolf.septposition.SeptPositionCreateView
characters.views.werewolf.septposition.SeptPositionUpdateView
characters.views.werewolf.totem.TotemCreateView
characters.views.werewolf.totem.TotemUpdateView
characters.views.werewolf.tribe.TribeCreateView
characters.views.werewolf.tribe.TribeUpdateView
characters.views.wraith.arcanos.ArcanosCreateView
characters.views.wraith.arcanos.ArcanosUpdateView
characters.views.wraith.faction.WraithFactionCreateView
characters.views.wraith.faction.WraithFactionUpdateView
characters.views.wraith.guild.GuildCreateView
characters.views.wraith.guild.GuildUpdateView
characters.views.wraith.shadow_archetype.ShadowArchetypeCreateView
characters.views.wraith.shadow_archetype.ShadowArchetypeUpdateView
characters.views.wraith.thorn.ThornCreateView
characters.views.wraith.thorn.ThornUpdateView
core.views.book.BookCreateView
core.views.book.BookUpdateView
core.views.houserules.HouseRuleCreateView
core.views.houserules.HouseRuleUpdateView
core.views.language.LanguageCreateView
core.views.language.LanguageUpdateView
core.views.newsitem.NewsItemCreateView
core.views.newsitem.NewsItemUpdateView
items.views.core.material.MaterialCreateView
items.views.core.material.MaterialUpdateView
items.views.core.medium.MediumCreateView
items.views.core.medium.MediumUpdateView
locations.views.mage.reality_zone.RealityZoneCreateView
locations.views.mage.reality_zone.RealityZoneUpdateView
    """.split()),
    'WIDGET': frozenset("""
widgets.views.auto_chained_ajax_view
    """.split()),
}

VIEW_POLICIES = {name: policy for policy, names in POLICIES.items() for name in names}
