from characters import views
from django.urls import path

urls = [
    path(
        "arcanos/<pk>/",
        views.wraith.ArcanosUpdateView.as_view(),
        name="arcanos",
    ),
    path(
        "circle/<pk>/",
        views.wraith.CircleUpdateView.as_view(),
        name="circle",
    ),
    path(
        "faction/<pk>/",
        views.wraith.WraithFactionUpdateView.as_view(),
        name="faction",
    ),
    path(
        "guild/<pk>/",
        views.wraith.GuildUpdateView.as_view(),
        name="guild",
    ),
    path(
        "shadow_archetype/<pk>/",
        views.wraith.ShadowArchetypeUpdateView.as_view(),
        name="shadow_archetype",
    ),
    path(
        "thorn/<pk>/",
        views.wraith.ThornUpdateView.as_view(),
        name="thorn",
    ),
    path(
        "wtohuman/<pk>/",
        views.wraith.WtOHumanUpdateView.as_view(),
        name="wto_human",
    ),
    path(
        "wto_human/full/<pk>/",
        views.wraith.WtOHumanUpdateView.as_view(),
        name="wto_human_full",
    ),
    path(
        "wraith/<pk>/",
        views.wraith.WraithCharacterCreationView.as_view(),
        name="wraith",
    ),
    path(
        "wraith/full/<pk>/",
        views.wraith.WraithUpdateView.as_view(),
        name="wraith_full",
    ),
]
