from characters import views
from django.urls import path

urls = [
    path(
        "charms/<pk>/",
        views.werewolf.SpiritCharmDetailView.as_view(),
        name="spirit_charm",
    ),
    path(
        "spirits/<pk>/",
        views.werewolf.SpiritDetailView.as_view(),
        name="spirit",
    ),
    path(
        "totems/<pk>/",
        views.werewolf.TotemDetailView.as_view(),
        name="totem",
    ),
    path("rites/<pk>/", views.werewolf.RiteDetailView.as_view(), name="rite"),
    path(
        "tribes/<pk>/",
        views.werewolf.TribeDetailView.as_view(),
        name="tribe",
    ),
    path("gifts/<pk>/", views.werewolf.GiftDetailView.as_view(), name="gift"),
    path(
        "battlescar/<pk>/",
        views.werewolf.BattleScarDetailView.as_view(),
        name="battlescar",
    ),
    path(
        "renownincidents/<pk>/",
        views.werewolf.RenownIncidentDetailView.as_view(),
        name="renownincident",
    ),
    path("camps/<pk>/", views.werewolf.CampDetailView.as_view(), name="camp"),
    path(
        "fomoripower/<pk>/",
        views.werewolf.FomoriPowerDetailView.as_view(),
        name="fomoripower",
    ),
    path(
        "fera/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="fera",
    ),
    path(
        "ratkin/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="ratkin",
    ),
    path(
        "mokole/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="mokole",
    ),
    path(
        "bastet/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="bastet",
    ),
    path(
        "corax/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="corax",
    ),
    path(
        "nuwisha/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="nuwisha",
    ),
    path(
        "gurahl/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="gurahl",
    ),
    path(
        "ananasi/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="ananasi",
    ),
    path(
        "rokea/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="rokea",
    ),
    path(
        "kitsune/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="kitsune",
    ),
    path(
        "nagah/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="nagah",
    ),
    path(
        "ajaba/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="ajaba",
    ),
    path(
        "grondr/<pk>/",
        views.werewolf.FeraDetailView.as_view(),
        name="grondr",
    ),
    path(
        "drone/<pk>/",
        views.werewolf.DroneDetailView.as_view(),
        name="drone",
    ),
    path(
        "septposition/<pk>/",
        views.werewolf.SeptPositionDetailView.as_view(),
        name="septposition",
    ),
    path(
        "wtahuman/<int:pk>/template/",
        views.werewolf.WtAHumanTemplateSelectView.as_view(),
        name="wtahuman_template",
    ),
    path(
        "wtahuman/<int:pk>/creation/",
        views.werewolf.WtAHumanCharacterCreationView.as_view(),
        name="wtahuman_creation",
    ),
]
