"""One declaration per routable model. Custom workflows live in views/."""

from core.model_registry import ActionSpec, ModelRegistry, ModelSpec

registry = ModelRegistry(
    "locations",
    [
        ModelSpec(
            model_label="locations.Tomb",
            slug="tomb",
            group="mummy",
            gameline="mtr",
            label="Tomb",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mummy.TombDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("tomb", "tomb/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mummy.TombListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("tomb", "tomb/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mummy.TombCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "contained_within",
                            "size",
                            "security",
                            "sanctity",
                            "era",
                            "has_false_chambers",
                            "has_hieroglyphic_wards",
                            "has_treasure_cache",
                            "has_sarcophagus",
                            "has_cult_shrine",
                            "has_underworld_portal",
                            "ba_per_week",
                            "guardian_description",
                            "original_occupant",
                            "discovered_date",
                            "archaeological_status",
                        ],
                        "success_message": "Tomb '{name}' created successfully!",
                        "error_message": "Failed to create tomb. Please correct the errors below.",
                    },
                    routes=[("tomb", "tomb/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.mummy.TombUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "contained_within",
                            "size",
                            "security",
                            "sanctity",
                            "era",
                            "has_false_chambers",
                            "has_hieroglyphic_wards",
                            "has_treasure_cache",
                            "has_sarcophagus",
                            "has_cult_shrine",
                            "has_underworld_portal",
                            "ba_per_week",
                            "duat_barrier",
                            "guardian_description",
                            "original_occupant",
                            "discovered_date",
                            "archaeological_status",
                        ],
                        "success_message": "Tomb '{name}' updated successfully!",
                        "error_message": "Failed to update tomb. Please correct the errors below.",
                    },
                    routes=[("tomb", "tomb/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:mummy:tomb",
                "update": "locations:mummy:update:tomb",
                "create": "locations:mummy:create:tomb",
                "list": "locations:mummy:list:tomb",
            },
            templates={
                "detail": "locations/mummy/tomb/detail.html",
                "list": "locations/mummy/tomb/list.html",
                "create": "locations/mummy/tomb/form.html",
                "update": "locations/mummy/tomb/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.CultTemple",
            slug="cult_temple",
            group="mummy",
            gameline="mtr",
            label="Cult Temple",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mummy.CultTempleDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("cult_temple", "cult_temple/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mummy.CultTempleListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("cult_temple", "cult_temple/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mummy.CultTempleCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Cult Temple '{name}' created successfully!",
                        "error_message": "Failed to create cult temple. Please correct the errors below.",
                    },
                    routes=[("cult_temple", "cult_temple/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.mummy.CultTempleUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Cult Temple '{name}' updated successfully!",
                        "error_message": "Failed to update cult temple. Please correct the errors below.",
                    },
                    routes=[("cult_temple", "cult_temple/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:mummy:cult_temple",
                "update": "locations:mummy:update:cult_temple",
                "create": "locations:mummy:create:cult_temple",
                "list": "locations:mummy:list:cult_temple",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "cult_size",
                "public_cover",
                "cult_leader_name",
                "cult_wealth",
                "has_library",
                "has_ritual_chamber",
            ),
            templates={
                "detail": "locations/mummy/cult_temple/detail.html",
                "list": "locations/mummy/cult_temple/list.html",
                "create": "locations/mummy/cult_temple/form.html",
                "update": "locations/mummy/cult_temple/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.UndergroundSanctuary",
            slug="underground_sanctuary",
            group="mummy",
            gameline="mtr",
            label="Underground Sanctuary",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mummy.UndergroundSanctuaryDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("sanctuary", "sanctuary/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mummy.UndergroundSanctuaryListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("sanctuary", "sanctuary/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mummy.UndergroundSanctuaryCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Sanctuary '{name}' created successfully!",
                        "error_message": "Failed to create sanctuary. Please correct the errors below.",
                    },
                    routes=[("sanctuary", "sanctuary/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.mummy.UndergroundSanctuaryUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Sanctuary '{name}' updated successfully!",
                        "error_message": "Failed to update sanctuary. Please correct the errors below.",
                    },
                    routes=[("sanctuary", "sanctuary/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:mummy:sanctuary",
                "update": "locations:mummy:update:sanctuary",
                "create": "locations:mummy:create:sanctuary",
                "list": "locations:mummy:list:sanctuary",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "sanctuary_type",
                "concealment_rating",
            ),
            templates={
                "detail": "locations/mummy/sanctuary/detail.html",
                "list": "locations/mummy/sanctuary/list.html",
                "create": "locations/mummy/sanctuary/form.html",
                "update": "locations/mummy/sanctuary/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.DreamRealm",
            slug="dream_realm",
            group="changeling",
            gameline="ctd",
            label="Dream Realm",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.changeling.dream_realm.DreamRealmDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("dream_realm", "dream_realm/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.changeling.dream_realm.DreamRealmListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("dream_realm", "dream_realm/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.changeling.dream_realm.DreamRealmCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("dream_realm", "dream_realm/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.changeling.dream_realm.DreamRealmUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("dream_realm", "dream_realm/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:changeling:dream_realm",
                "update": "locations:changeling:update:dream_realm",
                "create": "locations:changeling:create:dream_realm",
                "list": "locations:changeling:list:dream_realm",
            },
            form_class="locations.forms.changeling.dream_realm.DreamRealmForm",
            templates={
                "detail": "locations/changeling/dream_realm/detail.html",
                "list": "locations/changeling/dream_realm/list.html",
                "create": "locations/changeling/dream_realm/form.html",
                "update": "locations/changeling/dream_realm/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Freehold",
            slug="freehold",
            group="changeling",
            gameline="ctd",
            label="Freehold",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.changeling.freehold.FreeholdDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("freehold", "freehold/<int:pk>/")],
                    custom="locations.views.changeling.freehold._FreeholdDetailView",
                ),
                "list": ActionSpec(
                    view_path="locations.views.changeling.freehold.FreeholdListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("freehold", "freehold/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.changeling.freehold.FreeholdCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Freehold '{name}' created successfully!",
                        "error_message": "Failed to create freehold. Please correct the errors below.",
                    },
                    routes=[("freehold_direct", "freehold/direct/")],
                    custom="locations.views.changeling.freehold._FreeholdCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.changeling.freehold.FreeholdUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Freehold '{name}' updated successfully!",
                        "error_message": "Failed to update freehold. Please correct the errors below.",
                    },
                    routes=[("freehold_direct", "freehold/<int:pk>/direct/")],
                    custom="locations.views.changeling.freehold._FreeholdUpdateView",
                ),
            },
            model_urls={
                "detail": "locations:changeling:freehold",
                "update": "locations:changeling:update:freehold",
                "create": "locations:changeling:create:freehold",
                "list": "locations:changeling:list:freehold",
            },
            form_class="locations.forms.changeling.freehold.FreeholdForm",
            templates={
                "detail": "locations/changeling/freehold/detail.html",
                "list": "locations/changeling/freehold/list.html",
                "create": "locations/changeling/freehold/form.html",
                "update": "locations/changeling/freehold/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Holding",
            slug="holding",
            group="changeling",
            gameline="ctd",
            label="Holding",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.changeling.holding.HoldingDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("holding", "holding/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.changeling.holding.HoldingListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("holding", "holding/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.changeling.holding.HoldingCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("holding", "holding/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.changeling.holding.HoldingUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("holding", "holding/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:changeling:holding",
                "update": "locations:changeling:update:holding",
                "create": "locations:changeling:create:holding",
                "list": "locations:changeling:list:holding",
            },
            form_class="locations.forms.changeling.holding.HoldingForm",
            templates={
                "detail": "locations/changeling/holding/detail.html",
                "list": "locations/changeling/holding/list.html",
                "create": "locations/changeling/holding/form.html",
                "update": "locations/changeling/holding/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Trod",
            slug="trod",
            group="changeling",
            gameline="ctd",
            label="Trod",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.changeling.trod.TrodDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("trod", "trod/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.changeling.trod.TrodListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("trod", "trod/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.changeling.trod.TrodCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("trod", "trod/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.changeling.trod.TrodUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("trod", "trod/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:changeling:trod",
                "update": "locations:changeling:update:trod",
                "create": "locations:changeling:create:trod",
                "list": "locations:changeling:list:trod",
            },
            form_class="locations.forms.changeling.trod.TrodForm",
            templates={
                "detail": "locations/changeling/trod/detail.html",
                "list": "locations/changeling/trod/list.html",
                "create": "locations/changeling/trod/form.html",
                "update": "locations/changeling/trod/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.City",
            slug="city",
            group="core",
            gameline="wod",
            label="City",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.core.city.CityDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("city", "city/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.core.city.CityListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("city", "city/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.core.city.CityCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "City '{name}' created successfully!",
                        "error_message": "Failed to create city. Please correct the errors below.",
                    },
                    routes=[("city", "city/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "mood": {"attrs": {"placeholder": "Enter mood here"}},
                        "theme": {"attrs": {"placeholder": "Enter theme here"}},
                        "media": {"attrs": {"placeholder": "Enter media here"}},
                        "politicians": {"attrs": {"placeholder": "Enter politicians here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
                "update": ActionSpec(
                    view_path="locations.views.core.city.CityUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "City '{name}' updated successfully!",
                        "error_message": "Failed to update city. Please correct the errors below.",
                    },
                    routes=[("city", "city/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "mood": {"attrs": {"placeholder": "Enter mood here"}},
                        "theme": {"attrs": {"placeholder": "Enter theme here"}},
                        "media": {"attrs": {"placeholder": "Enter media here"}},
                        "politicians": {"attrs": {"placeholder": "Enter politicians here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:update:city",
                "create": "locations:create:city",
                "list": "locations:list:city",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "gauntlet",
                "shroud",
                "dimension_barrier",
                "population",
                "mood",
                "theme",
                "media",
                "politicians",
                "characters",
            ),
            templates={
                "detail": "locations/core/city/detail.html",
                "list": "locations/core/city/list.html",
                "create": "locations/core/city/form.html",
                "update": "locations/core/city/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.LocationModel",
            slug="location",
            group="core",
            gameline="wod",
            label="Location",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.core.location.LocationDetailView",
                    policy="OBJECT_DETAIL",
                ),
                "list": ActionSpec(
                    view_path="locations.views.core.location.LocationListView",
                    policy="OBJECT_LIST",
                    routes=[("location", "location/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.core.location.LocationCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "contained_within",
                            "gauntlet",
                            "shroud",
                            "dimension_barrier",
                            "description",
                        ],
                        "success_message": "Location '{name}' created successfully!",
                        "error_message": "Failed to create location. Please correct the errors below.",
                    },
                    routes=[("location", "location/")],
                    custom="locations.views.core.location._LocationCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.core.location.LocationUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "contained_within",
                            "gauntlet",
                            "shroud",
                            "dimension_barrier",
                            "description",
                        ],
                        "success_message": "Location '{name}' updated successfully!",
                        "error_message": "Failed to update location. Please correct the errors below.",
                    },
                    routes=[("location", "location/<int:pk>/")],
                    custom="locations.views.core.location._LocationUpdateView",
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:update:location",
                "create": "locations:create:location",
                "list": "locations:list:location",
            },
            templates={
                "detail": "locations/core/location/detail.html",
                "create": "locations/core/location/form.html",
                "update": "locations/core/location/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Bastion",
            slug="bastion",
            group="demon",
            gameline="dtf",
            label="Bastion",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.demon.bastion.BastionDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("bastion", "bastion/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.demon.bastion.BastionListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("bastion", "bastion/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.demon.bastion.BastionCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "contained_within",
                            "description",
                            "ritual_strength",
                            "warding_level",
                            "consecration_date",
                        ],
                        "success_message": "Bastion '{name}' created successfully!",
                        "error_message": "Failed to create bastion. Please correct the errors below.",
                    },
                    routes=[("bastion", "bastion/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
                "update": ActionSpec(
                    view_path="locations.views.demon.bastion.BastionUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "contained_within",
                            "ritual_strength",
                            "warding_level",
                            "consecration_date",
                        ],
                        "success_message": "Bastion '{name}' updated successfully!",
                        "error_message": "Failed to update bastion. Please correct the errors below.",
                    },
                    routes=[("bastion", "bastion/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
            },
            model_urls={
                "detail": "locations:demon:bastion",
                "update": "locations:demon:update:bastion",
                "create": "locations:demon:create:bastion",
                "list": "locations:demon:list:bastion",
            },
            templates={
                "detail": "locations/demon/bastion/detail.html",
                "list": "locations/demon/bastion/list.html",
                "create": "locations/demon/bastion/form.html",
                "update": "locations/demon/bastion/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Reliquary",
            slug="reliquary",
            group="demon",
            gameline="dtf",
            label="Reliquary",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.demon.reliquary.ReliquaryDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("reliquary", "reliquary/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.demon.reliquary.ReliquaryListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("reliquary", "reliquary/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.demon.reliquary.ReliquaryCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "name",
                            "contained_within",
                            "description",
                            "reliquary_type",
                            "location_size",
                            "max_health_levels",
                            "current_health_levels",
                            "soak_rating",
                            "has_pervasiveness",
                            "has_manifestation",
                            "manifestation_range",
                        ],
                        "success_message": "Reliquary '{name}' created successfully!",
                        "error_message": "Failed to create reliquary. Please correct the errors below.",
                    },
                    routes=[("reliquary", "reliquary/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
                "update": ActionSpec(
                    view_path="locations.views.demon.reliquary.ReliquaryUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "contained_within",
                            "reliquary_type",
                            "location_size",
                            "max_health_levels",
                            "current_health_levels",
                            "soak_rating",
                            "has_pervasiveness",
                            "has_manifestation",
                            "manifestation_range",
                        ],
                        "success_message": "Reliquary '{name}' updated successfully!",
                        "error_message": "Failed to update reliquary. Please correct the errors below.",
                    },
                    routes=[("reliquary", "reliquary/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
            },
            model_urls={
                "detail": "locations:demon:reliquary",
                "update": "locations:demon:update:reliquary",
                "create": "locations:demon:create:reliquary",
                "list": "locations:demon:list:reliquary",
            },
            templates={
                "detail": "locations/demon/reliquary/detail.html",
                "list": "locations/demon/reliquary/list.html",
                "create": "locations/demon/reliquary/form.html",
                "update": "locations/demon/reliquary/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.HuntingGround",
            slug="hunting_ground",
            group="hunter",
            gameline="htr",
            label="Hunting Ground",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.hunter.huntingground.HuntingGroundDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("hunting_ground", "hunting-ground/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.hunter.huntingground.HuntingGroundListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("hunting_ground", "hunting-grounds/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.hunter.huntingground.HuntingGroundCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Hunting Ground '{name}' created successfully!",
                        "error_message": "Failed to create hunting ground. Please correct the errors below.",
                    },
                    routes=[("hunting_ground", "hunting-ground/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.hunter.huntingground.HuntingGroundUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Hunting Ground '{name}' updated successfully!",
                        "error_message": "Failed to update hunting ground. Please correct the errors below.",
                    },
                    routes=[("hunting_ground", "hunting-ground/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:hunter:update:hunting_ground",
                "create": "locations:hunter:create:hunting_ground",
                "list": "locations:hunter:list:hunting_ground",
            },
            fields=(
                "name",
                "contained_within",
                "description",
                "size",
                "population",
                "supernatural_activity",
                "primary_threat",
                "threat_description",
                "is_contested",
                "control_level",
                "contact_network",
                "surveillance_coverage",
                "last_incident",
                "incident_log",
                "key_locations",
            ),
            templates={
                "detail": "locations/hunter/huntingground/detail.html",
                "list": "locations/hunter/huntingground/list.html",
                "create": "locations/hunter/huntingground/form.html",
                "update": "locations/hunter/huntingground/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Safehouse",
            slug="safehouse",
            group="hunter",
            gameline="htr",
            label="Safehouse",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.hunter.safehouse.SafehouseDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("safehouse", "safehouse/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.hunter.safehouse.SafehouseListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("safehouse", "safehouses/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.hunter.safehouse.SafehouseCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Safehouse '{name}' created successfully!",
                        "error_message": "Failed to create safehouse. Please correct the errors below.",
                    },
                    routes=[("safehouse", "safehouse/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.hunter.safehouse.SafehouseUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Safehouse '{name}' updated successfully!",
                        "error_message": "Failed to update safehouse. Please correct the errors below.",
                    },
                    routes=[("safehouse", "safehouse/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:hunter:update:safehouse",
                "create": "locations:hunter:create:safehouse",
                "list": "locations:hunter:list:safehouse",
            },
            fields=(
                "name",
                "contained_within",
                "description",
                "size",
                "capacity",
                "security_level",
                "armory_level",
                "surveillance_level",
                "medical_facilities",
                "is_compromised",
                "is_mobile",
                "has_panic_room",
                "has_escape_routes",
                "has_dead_drop",
                "has_communications",
                "cover_story",
                "legal_owner",
            ),
            templates={
                "detail": "locations/hunter/safehouse/detail.html",
                "list": "locations/hunter/safehouse/list.html",
                "create": "locations/hunter/safehouse/form.html",
                "update": "locations/hunter/safehouse/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Chantry",
            slug="chantry",
            group="mage",
            gameline="mta",
            label="Chantry",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.chantry.ChantryDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("chantry", "chantry/<int:pk>/")],
                    custom="locations.views.mage.chantry._ChantryDetailView",
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.chantry.ChantryListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("chantry", "chantry/")],
                    custom="locations.views.mage.chantry._ChantryListView",
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.chantry.ChantryCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": [
                            "chronicle",
                            "name",
                            "contained_within",
                            "gauntlet",
                            "shroud",
                            "dimension_barrier",
                            "description",
                            "faction",
                            "leadership_type",
                            "season",
                            "chantry_type",
                            "total_points",
                            "integrated_effects",
                            "leaders",
                            "members",
                            "cabals",
                            "ambassador",
                            "node_tender",
                            "investigator",
                            "guardian",
                            "teacher",
                        ],
                        "success_message": "Chantry '{name}' created successfully!",
                        "error_message": "Failed to create chantry. Please correct the errors below.",
                    },
                    routes=[("chantry_direct", "chantry/direct/")],
                    custom="locations.views.mage.chantry._ChantryCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.chantry.ChantryUpdateView",
                    policy="OBJECT_ST_WRITE",
                    options={
                        "fields": [
                            "name",
                            "contained_within",
                            "gauntlet",
                            "shroud",
                            "dimension_barrier",
                            "description",
                            "faction",
                            "leadership_type",
                            "season",
                            "chantry_type",
                            "total_points",
                            "integrated_effects",
                            "leaders",
                            "members",
                            "cabals",
                            "ambassador",
                            "node_tender",
                            "investigator",
                            "guardian",
                            "teacher",
                        ],
                        "success_message": "Chantry '{name}' updated successfully!",
                        "error_message": "Failed to update chantry. Please correct the errors below.",
                    },
                    routes=[("chantry", "chantry/<int:pk>/")],
                    custom="locations.views.mage.chantry._ChantryUpdateView",
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:chantry",
                "create": "locations:mage:create:chantry",
                "list": "locations:mage:list:chantry",
            },
            templates={
                "detail": "locations/mage/chantry/detail.html",
                "list": "locations/mage/chantry/list.html",
                "create": "locations/mage/chantry/form.html",
                "update": "locations/mage/chantry/form.html",
            },
            dispatch_view="locations.views.mage.chantry.ChantryCreationView",
        ),
        ModelSpec(
            model_label="locations.Demesne",
            slug="demesne",
            group="mage",
            gameline="mta",
            label="Demesne",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.demesne.DemesneDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("demesne", "demesne/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.demesne.DemesneListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("demesne", "demesne/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.demesne.DemesneCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Demesne '{name}' created successfully!",
                        "error_message": "Failed to create demesne. Please correct the errors below.",
                        "form_class": "locations.forms.mage.demesne.DemesneForm",
                    },
                    routes=[("demesne", "demesne/")],
                    custom="locations.views.mage.demesne._DemesneCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.demesne.DemesneUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "contained_within",
                            "size",
                            "accessibility",
                        ],
                        "success_message": "Demesne '{name}' updated successfully!",
                        "error_message": "Failed to update demesne. Please correct the errors below.",
                    },
                    routes=[("demesne", "demesne/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:demesne",
                "create": "locations:mage:create:demesne",
                "list": "locations:mage:list:demesne",
            },
            templates={
                "detail": "locations/mage/demesne/detail.html",
                "list": "locations/mage/demesne/list.html",
                "create": "locations/mage/demesne/form.html",
                "update": "locations/mage/demesne/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Library",
            slug="library",
            group="mage",
            gameline="mta",
            label="Library",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.library.LibraryDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("library", "library/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.library.LibraryListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("library", "library/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.library.LibraryCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Library '{name}' created successfully!",
                        "error_message": "Failed to create library. Please correct the errors below.",
                        "form_class": "locations.forms.mage.library.LibraryForm",
                    },
                    routes=[("library", "library/")],
                    custom="locations.views.mage.library._LibraryCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.library.LibraryUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": [
                            "name",
                            "description",
                            "contained_within",
                            "rank",
                            "faction",
                            "books",
                        ],
                        "success_message": "Library '{name}' updated successfully!",
                        "error_message": "Failed to update library. Please correct the errors below.",
                    },
                    routes=[("library", "library/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                    },
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:library",
                "create": "locations:mage:create:library",
                "list": "locations:mage:list:library",
            },
            templates={
                "detail": "locations/mage/library/detail.html",
                "list": "locations/mage/library/list.html",
                "create": "locations/mage/library/form.html",
                "update": "locations/mage/library/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Node",
            slug="node",
            group="mage",
            gameline="mta",
            label="Node",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.node.NodeDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("node", "node/<int:pk>/")],
                    custom="locations.views.mage.node._NodeDetailView",
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.node.NodeListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("node", "node/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.node.NodeCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Node '{name}' created successfully!",
                        "error_message": "Failed to create node. Please correct the errors below.",
                    },
                    routes=[("node", "node/")],
                    custom="locations.views.mage.node._NodeCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.node.NodeUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Node '{name}' updated successfully!",
                        "error_message": "Failed to update node. Please correct the errors below.",
                    },
                    routes=[("node", "node/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:node",
                "create": "locations:mage:create:node",
                "list": "locations:mage:list:node",
            },
            form_class="locations.forms.mage.node.NodeForm",
            templates={
                "detail": "locations/mage/node/detail.html",
                "list": "locations/mage/node/list.html",
                "create": "locations/mage/node/form.html",
                "update": "locations/mage/node/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.ParadoxRealm",
            slug="paradox_realm",
            group="mage",
            gameline="mta",
            label="Paradox Realm",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.paradox_realm.ParadoxRealmDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("paradox_realm", "paradox_realm/<int:pk>/")],
                    custom="locations.views.mage.paradox_realm._ParadoxRealmDetailView",
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.paradox_realm.ParadoxRealmListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("paradox_realm", "paradox_realm/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.paradox_realm.ParadoxRealmCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Paradox Realm '{name}' created successfully!",
                        "error_message": "Failed to create paradox realm. Please correct the errors below.",
                    },
                    routes=[("paradox_realm", "paradox_realm/")],
                    custom="locations.views.mage.paradox_realm._ParadoxRealmCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.paradox_realm.ParadoxRealmUpdateView",
                    policy="OBJECT_ACTION",
                    options={
                        "success_message": "Paradox Realm '{name}' updated successfully!",
                        "error_message": "Failed to update paradox realm. Please correct the errors below.",
                    },
                    routes=[("paradox_realm", "paradox_realm/<int:pk>/")],
                    custom="locations.views.mage.paradox_realm._ParadoxRealmUpdateView",
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:paradox_realm",
                "create": "locations:mage:create:paradox_realm",
                "list": "locations:mage:list:paradox_realm",
            },
            form_class="locations.forms.mage.paradox_realm.ParadoxRealmForm",
            templates={
                "detail": "locations/mage/paradox_realm/detail.html",
                "list": "locations/mage/paradox_realm/list.html",
                "create": "locations/mage/paradox_realm/form.html",
                "update": "locations/mage/paradox_realm/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.HorizonRealm",
            slug="horizon_realm",
            group="mage",
            gameline="mta",
            label="Horizon Realm",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.realm.RealmDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("horizon_realm", "horizon_realm/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.realm.RealmListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("horizon_realm", "horizon_realm/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.realm.RealmCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Horizon Realm '{name}' created successfully!",
                        "error_message": "Failed to create horizon realm. Please correct the errors below.",
                    },
                    routes=[("horizon_realm", "realm/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.realm.RealmUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Horizon Realm '{name}' updated successfully!",
                        "error_message": "Failed to update horizon realm. Please correct the errors below.",
                    },
                    routes=[("horizon_realm", "realm/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:horizon_realm",
                "create": "locations:mage:create:horizon_realm",
                "list": "locations:mage:list:horizon_realm",
            },
            fields=("name", "description", "contained_within"),
            templates={
                "detail": "locations/mage/realm/detail.html",
                "list": "locations/mage/realm/list.html",
                "create": "locations/mage/realm/form.html",
                "update": "locations/mage/realm/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Sanctum",
            slug="sanctum",
            group="mage",
            gameline="mta",
            label="Sanctum",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.sanctum.SanctumDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("sanctum", "sanctum/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.sanctum.SanctumListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("sanctum", "sanctum/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.sanctum.SanctumCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Sanctum '{name}' created successfully!",
                        "error_message": "Failed to create sanctum. Please correct the errors below.",
                    },
                    routes=[("sanctum", "sanctum/")],
                    custom="locations.views.mage.sanctum._SanctumCreateView",
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.sanctum.SanctumUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Sanctum '{name}' updated successfully!",
                        "error_message": "Failed to update sanctum. Please correct the errors below.",
                    },
                    routes=[("sanctum", "sanctum/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:sanctum",
                "create": "locations:mage:create:sanctum",
                "list": "locations:mage:list:sanctum",
            },
            form_class="locations.forms.mage.sanctum.SanctumForm",
            templates={
                "detail": "locations/mage/sanctum/detail.html",
                "list": "locations/mage/sanctum/list.html",
                "create": "locations/mage/sanctum/form.html",
                "update": "locations/mage/sanctum/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Sector",
            slug="sector",
            group="mage",
            gameline="mta",
            label="Sector",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.mage.sector.SectorDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("sector", "sector/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.mage.sector.SectorListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("sector", "sector/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.mage.sector.SectorCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Sector '{name}' created successfully!",
                        "error_message": "Failed to create sector. Please correct the errors below.",
                    },
                    routes=[("sector", "sector/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.mage.sector.SectorUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Sector '{name}' updated successfully!",
                        "error_message": "Failed to update sector. Please correct the errors below.",
                    },
                    routes=[("sector", "sector/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:mage:update:sector",
                "create": "locations:mage:create:sector",
                "list": "locations:mage:list:sector",
            },
            form_class="locations.forms.mage.sector.SectorForm",
            templates={
                "detail": "locations/mage/sector/detail.html",
                "list": "locations/mage/sector/list.html",
                "create": "locations/mage/sector/form.html",
                "update": "locations/mage/sector/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Haven",
            slug="haven",
            group="vampire",
            gameline="vtm",
            label="Haven",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.vampire.HavenDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("haven", "haven/<int:pk>/")],
                    custom="locations.views.vampire._HavenDetailView",
                ),
                "list": ActionSpec(
                    view_path="locations.views.vampire.HavenListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("haven", "havens/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.vampire.HavenCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Haven '{name}' created successfully!",
                        "error_message": "Failed to create haven. Please correct the errors below.",
                    },
                    routes=[("haven", "haven/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.vampire.HavenUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Haven '{name}' updated successfully!",
                        "error_message": "Failed to update haven. Please correct the errors below.",
                    },
                    routes=[("haven", "haven/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:vampire:update:haven",
                "create": "locations:vampire:create:haven",
                "list": "locations:vampire:list:haven",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "size",
                "security",
                "location",
                "has_guardian",
                "has_luxury",
                "is_hidden",
                "has_library",
                "has_workshop",
            ),
            templates={
                "detail": "locations/vampire/haven/detail.html",
                "list": "locations/vampire/haven/list.html",
                "create": "locations/vampire/haven/form.html",
                "update": "locations/vampire/haven/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Domain",
            slug="domain",
            group="vampire",
            gameline="vtm",
            label="Domain",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.vampire.DomainDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("domain", "domain/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.vampire.DomainListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("domain", "domains/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.vampire.DomainCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Domain '{name}' created successfully!",
                        "error_message": "Failed to create domain. Please correct the errors below.",
                    },
                    routes=[("domain", "domain/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.vampire.DomainUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Domain '{name}' updated successfully!",
                        "error_message": "Failed to update domain. Please correct the errors below.",
                    },
                    routes=[("domain", "domain/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:vampire:domain",
                "update": "locations:vampire:update:domain",
                "create": "locations:vampire:create:domain",
                "list": "locations:vampire:list:domain",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "size",
                "population",
                "control",
                "is_elysium",
                "has_rack",
                "is_disputed",
                "domain_type",
            ),
            templates={
                "detail": "locations/vampire/domain/detail.html",
                "list": "locations/vampire/domain/list.html",
                "create": "locations/vampire/domain/form.html",
                "update": "locations/vampire/domain/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Elysium",
            slug="elysium",
            group="vampire",
            gameline="vtm",
            label="Elysium",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.vampire.ElysiumDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("elysium", "elysium/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.vampire.ElysiumListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("elysium", "elysiums/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.vampire.ElysiumCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Elysium '{name}' created successfully!",
                        "error_message": "Failed to create elysium. Please correct the errors below.",
                    },
                    routes=[("elysium", "elysium/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.vampire.ElysiumUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Elysium '{name}' updated successfully!",
                        "error_message": "Failed to update elysium. Please correct the errors below.",
                    },
                    routes=[("elysium", "elysium/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:vampire:update:elysium",
                "create": "locations:vampire:create:elysium",
                "list": "locations:vampire:list:elysium",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "prestige",
                "keeper_name",
                "elysium_type",
                "is_protected",
                "allows_weapons",
                "has_blood_dolls",
                "has_art_collection",
                "has_library",
                "is_court",
            ),
            templates={
                "detail": "locations/vampire/elysium/detail.html",
                "list": "locations/vampire/elysium/list.html",
                "create": "locations/vampire/elysium/form.html",
                "update": "locations/vampire/elysium/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Rack",
            slug="rack",
            group="vampire",
            gameline="vtm",
            label="Rack",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.vampire.RackDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("rack", "rack/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.vampire.RackListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("rack", "racks/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.vampire.RackCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Rack '{name}' created successfully!",
                        "error_message": "Failed to create rack. Please correct the errors below.",
                    },
                    routes=[("rack", "rack/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.vampire.RackUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Rack '{name}' updated successfully!",
                        "error_message": "Failed to update rack. Please correct the errors below.",
                    },
                    routes=[("rack", "rack/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:vampire:update:rack",
                "create": "locations:vampire:create:rack",
                "list": "locations:vampire:list:rack",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "quality",
                "population_density",
                "risk_level",
                "rack_type",
                "blood_quality",
                "is_protected",
                "is_exclusive",
                "is_contested",
                "masquerade_risk",
            ),
            templates={
                "detail": "locations/vampire/rack/detail.html",
                "list": "locations/vampire/rack/list.html",
                "create": "locations/vampire/rack/form.html",
                "update": "locations/vampire/rack/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.TremereChantry",
            slug="tremere_chantry",
            group="vampire",
            gameline="vtm",
            label="Tremere Chantry",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.vampire.TremereChantryDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("chantry", "chantry/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.vampire.TremereChantryListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("tremere_chantry", "tremere_chantry/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.vampire.TremereChantryCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("chantry", "chantry/"), ("tremere_chantry", "tremere_chantry/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.vampire.TremereChantryUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("chantry", "chantry/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:vampire:update:chantry",
                "create": "locations:vampire:create:chantry",
                "list": "locations:vampire:list:tremere_chantry",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "size",
                "security_level",
                "library_rating",
                "ritual_rooms",
                "blood_vault_capacity",
                "regent_name",
                "resident_count",
                "apprentice_count",
                "has_wards",
                "has_sanctum",
                "has_blood_forge",
                "has_scrying_chamber",
                "has_gargoyle_guardians",
                "pyramid_level",
                "reports_to",
            ),
            templates={
                "detail": "locations/vampire/chantry/detail.html",
                "list": "locations/vampire/chantry/list.html",
                "create": "locations/vampire/chantry/form.html",
                "update": "locations/vampire/chantry/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Barrens",
            slug="barrens",
            group="vampire",
            gameline="vtm",
            label="Barrens",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.vampire.BarrensDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("barrens", "barrens/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.vampire.BarrensListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("barrens", "barrens/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.vampire.BarrensCreateView",
                    policy="OBJECT_CREATE",
                    routes=[("barrens", "barrens/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.vampire.BarrensUpdateView",
                    policy="OBJECT_WRITE",
                    routes=[("barrens", "barrens/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:vampire:update:barrens",
                "create": "locations:vampire:create:barrens",
                "list": "locations:vampire:list:barrens",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "size",
                "danger_level",
                "population_density",
                "is_contested",
                "is_anarch_territory",
                "is_sabbat_territory",
                "is_unclaimed",
                "controlling_faction",
                "has_feeding_grounds",
                "feeding_quality",
                "has_shelter",
                "has_resources",
                "masquerade_threat",
                "lupine_activity",
                "hunter_activity",
                "mortal_gang_activity",
                "barrens_type",
                "notable_locations",
            ),
            templates={
                "detail": "locations/vampire/barrens/detail.html",
                "list": "locations/vampire/barrens/list.html",
                "create": "locations/vampire/barrens/form.html",
                "update": "locations/vampire/barrens/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Caern",
            slug="caern",
            group="werewolf",
            gameline="wta",
            label="Caern",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.werewolf.caern.CaernDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("caern", "caern/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.werewolf.caern.CaernListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("caern", "caern/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.werewolf.caern.CaernCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "fields": ["name", "contained_within", "description", "rank", "caern_type"],
                        "success_message": "Caern '{name}' created successfully!",
                        "error_message": "Failed to create caern. Please correct the errors below.",
                    },
                    routes=[("caern", "caern/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
                "update": ActionSpec(
                    view_path="locations.views.werewolf.caern.CaernUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "fields": ["name", "description", "contained_within", "rank", "caern_type"],
                        "success_message": "Caern '{name}' updated successfully!",
                        "error_message": "Failed to update caern. Please correct the errors below.",
                    },
                    routes=[("caern", "caern/<int:pk>/")],
                    form_updates={
                        "name": {"attrs": {"placeholder": "Enter name here"}},
                        "description": {"attrs": {"placeholder": "Enter description here"}},
                        "contained_within": {"help_text": "Select one or more parent locations"},
                    },
                ),
            },
            model_urls={
                "detail": "locations:location",
                "update": "locations:werewolf:update:caern",
                "create": "locations:werewolf:create:caern",
                "list": "locations:werewolf:list:caern",
            },
            templates={
                "detail": "locations/werewolf/caern/detail.html",
                "list": "locations/werewolf/caern/list.html",
                "create": "locations/werewolf/caern/form.html",
                "update": "locations/werewolf/caern/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Byway",
            slug="byway",
            group="wraith",
            gameline="wto",
            label="Byway",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.wraith.byway.BywayDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("byway", "byway/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.wraith.byway.BywayListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("byway", "byway/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.wraith.byway.BywayCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Byway '{name}' created successfully!",
                        "error_message": "Failed to create byway. Please correct the errors below.",
                    },
                    routes=[("byway", "byway/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.wraith.byway.BywayUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Byway '{name}' updated successfully!",
                        "error_message": "Failed to update byway. Please correct the errors below.",
                    },
                    routes=[("byway", "byway/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:wraith:byway",
                "update": "locations:wraith:update:byway",
                "create": "locations:wraith:create:byway",
                "list": "locations:wraith:list:byway",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "danger_level",
                "stability",
                "origin",
                "destination",
                "travel_time",
                "maelstrom_proximity",
                "spectral_activity",
                "has_waystation",
                "patrolled",
                "haunted",
            ),
            templates={
                "detail": "locations/wraith/byway/detail.html",
                "list": "locations/wraith/byway/list.html",
                "create": "locations/wraith/byway/form.html",
                "update": "locations/wraith/byway/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Citadel",
            slug="citadel",
            group="wraith",
            gameline="wto",
            label="Citadel",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.wraith.citadel.CitadelDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("citadel", "citadel/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.wraith.citadel.CitadelListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("citadel", "citadel/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.wraith.citadel.CitadelCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Citadel '{name}' created successfully!",
                        "error_message": "Failed to create citadel. Please correct the errors below.",
                    },
                    routes=[("citadel", "citadel/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.wraith.citadel.CitadelUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Citadel '{name}' updated successfully!",
                        "error_message": "Failed to update citadel. Please correct the errors below.",
                    },
                    routes=[("citadel", "citadel/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:wraith:citadel",
                "update": "locations:wraith:update:citadel",
                "create": "locations:wraith:create:citadel",
                "list": "locations:wraith:list:citadel",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "purpose",
                "defense_rating",
                "garrison_size",
                "commander",
                "controlling_faction",
                "has_soulforges",
                "has_prison",
                "has_gateway",
            ),
            templates={
                "detail": "locations/wraith/citadel/detail.html",
                "list": "locations/wraith/citadel/list.html",
                "create": "locations/wraith/citadel/form.html",
                "update": "locations/wraith/citadel/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.WraithFreehold",
            slug="wraith_freehold",
            group="wraith",
            gameline="wto",
            label="Wraith Freehold",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.wraith.freehold.WraithFreeholdDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("freehold", "freehold/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.wraith.freehold.WraithFreeholdListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("freehold", "freehold/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.wraith.freehold.WraithFreeholdCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Wraith Freehold '{name}' created successfully!",
                        "error_message": "Failed to create freehold. Please correct the errors below.",
                    },
                    routes=[("freehold", "freehold/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.wraith.freehold.WraithFreeholdUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Wraith Freehold '{name}' updated successfully!",
                        "error_message": "Failed to update freehold. Please correct the errors below.",
                    },
                    routes=[("freehold", "freehold/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:wraith:freehold",
                "update": "locations:wraith:update:freehold",
                "create": "locations:wraith:create:freehold",
                "list": "locations:wraith:list:freehold",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "population",
                "government_type",
                "leader",
                "hierarchy_relation",
                "allied_factions",
                "defense_rating",
                "resource_level",
                "has_soulforges",
                "has_library",
                "has_safe_passage",
                "hidden",
                "founding_principle",
            ),
            templates={
                "detail": "locations/wraith/freehold/detail.html",
                "list": "locations/wraith/freehold/list.html",
                "create": "locations/wraith/freehold/form.html",
                "update": "locations/wraith/freehold/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Haunt",
            slug="haunt",
            group="wraith",
            gameline="wto",
            label="Haunt",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.wraith.haunt.HauntDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("haunt", "haunt/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.wraith.haunt.HauntListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("haunt", "haunt/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.wraith.haunt.HauntCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Haunt '{name}' created successfully!",
                        "error_message": "Failed to create haunt. Please correct the errors below.",
                    },
                    routes=[("haunt", "haunt/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.wraith.haunt.HauntUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Haunt '{name}' updated successfully!",
                        "error_message": "Failed to update haunt. Please correct the errors below.",
                    },
                    routes=[("haunt", "haunt/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:wraith:haunt",
                "update": "locations:wraith:update:haunt",
                "create": "locations:wraith:create:haunt",
                "list": "locations:wraith:list:haunt",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "rank",
                "shroud_rating",
                "haunt_type",
                "haunt_size",
                "faith_resonance",
                "attracts_ghosts",
            ),
            templates={
                "detail": "locations/wraith/haunt/detail.html",
                "list": "locations/wraith/haunt/list.html",
                "create": "locations/wraith/haunt/form.html",
                "update": "locations/wraith/haunt/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Necropolis",
            slug="necropolis",
            group="wraith",
            gameline="wto",
            label="Necropolis",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.wraith.necropolis.NecropolisDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("necropolis", "necropolis/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.wraith.necropolis.NecropolisListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("necropolis", "necropolis/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.wraith.necropolis.NecropolisCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Necropolis '{name}' created successfully!",
                        "error_message": "Failed to create necropolis. Please correct the errors below.",
                    },
                    routes=[("necropolis", "necropolis/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.wraith.necropolis.NecropolisUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Necropolis '{name}' updated successfully!",
                        "error_message": "Failed to update necropolis. Please correct the errors below.",
                    },
                    routes=[("necropolis", "necropolis/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:wraith:necropolis",
                "update": "locations:wraith:update:necropolis",
                "create": "locations:wraith:create:necropolis",
                "list": "locations:wraith:list:necropolis",
            },
            fields=("name", "description", "contained_within", "region", "population", "deathlord"),
            templates={
                "detail": "locations/wraith/necropolis/detail.html",
                "list": "locations/wraith/necropolis/list.html",
                "create": "locations/wraith/necropolis/form.html",
                "update": "locations/wraith/necropolis/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.Nihil",
            slug="nihil",
            group="wraith",
            gameline="wto",
            label="Nihil",
            actions={
                "detail": ActionSpec(
                    view_path="locations.views.wraith.nihil.NihilDetailView",
                    policy="OBJECT_DETAIL",
                    routes=[("nihil", "nihil/<int:pk>/")],
                ),
                "list": ActionSpec(
                    view_path="locations.views.wraith.nihil.NihilListView",
                    policy="OBJECT_LIST",
                    options={"ordering": ["name"]},
                    routes=[("nihil", "nihil/")],
                ),
                "create": ActionSpec(
                    view_path="locations.views.wraith.nihil.NihilCreateView",
                    policy="OBJECT_CREATE",
                    options={
                        "success_message": "Nihil '{name}' created successfully!",
                        "error_message": "Failed to create nihil. Please correct the errors below.",
                    },
                    routes=[("nihil", "nihil/")],
                ),
                "update": ActionSpec(
                    view_path="locations.views.wraith.nihil.NihilUpdateView",
                    policy="OBJECT_WRITE",
                    options={
                        "success_message": "Nihil '{name}' updated successfully!",
                        "error_message": "Failed to update nihil. Please correct the errors below.",
                    },
                    routes=[("nihil", "nihil/<int:pk>/")],
                ),
            },
            model_urls={
                "detail": "locations:wraith:nihil",
                "update": "locations:wraith:update:nihil",
                "create": "locations:wraith:create:nihil",
                "list": "locations:wraith:list:nihil",
            },
            fields=(
                "name",
                "description",
                "contained_within",
                "void_type",
                "stability",
                "hazard_level",
                "oblivion_proximity",
                "entropy_rating",
                "estimated_size",
                "corpus_drain",
                "pathos_drain",
                "memory_loss",
                "shadow_attraction",
                "avoidable",
                "marked",
                "spectral_activity",
                "contains_relics",
                "origin_story",
            ),
            templates={
                "detail": "locations/wraith/nihil/detail.html",
                "list": "locations/wraith/nihil/list.html",
                "create": "locations/wraith/nihil/form.html",
                "update": "locations/wraith/nihil/form.html",
            },
        ),
        ModelSpec(
            model_label="locations.RealityZone",
            slug="reality_zone",
            group="mage",
            gameline="mta",
            label="Reality Zone",
            fields=("name", "description", "practices"),
            actions={
                "detail": ActionSpec(
                    "locations.views.mage.reality_zone.RealityZoneDetailView",
                    "PUBLIC_READ",
                    custom="locations.views.mage.reality_zone._RealityZoneDetailView",
                    routes=(("reality_zone", "reality_zone/<int:pk>/"),),
                ),
                "list": ActionSpec(
                    "locations.views.mage.reality_zone.RealityZoneListView",
                    "PUBLIC_READ",
                    routes=(("reality_zone", "reality_zone/"),),
                ),
                "create": ActionSpec(
                    "locations.views.mage.reality_zone.RealityZoneCreateView",
                    "STAFF_WRITE",
                    routes=(("reality_zone", "reality_zone/"),),
                ),
                "update": ActionSpec(
                    "locations.views.mage.reality_zone.RealityZoneUpdateView",
                    "STAFF_WRITE",
                    routes=(("reality_zone", "reality_zone/<int:pk>/"),),
                ),
            },
            templates={
                "detail": "locations/mage/reality_zone/detail.html",
                "list": "locations/mage/reality_zone/list.html",
                "create": "locations/mage/reality_zone/form.html",
                "update": "locations/mage/reality_zone/form.html",
            },
            model_urls={
                "detail": "locations:mage:reality_zone",
                "list": "locations:mage:list:reality_zone",
                "create": "locations:mage:create:reality_zone",
                "update": "locations:mage:update:reality_zone",
            },
        ),
    ],
)
