from characters.models.demon import Demon
from core.mixins import (
    ApprovedUserContextMixin,
    EditPermissionMixin,
    MessageMixin,
    SpendFreebiesPermissionMixin,
    SpendXPPermissionMixin,
    ViewPermissionMixin,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, UpdateView


class DemonDetailView(ApprovedUserContextMixin, ViewPermissionMixin, DetailView):
    model = Demon
    template_name = "characters/demon/demon/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DemonCreateView(MessageMixin, CreateView):
    model = Demon
    fields = [
        "name",
        "description",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "perception",
        "intelligence",
        "wits",
        "charisma",
        "manipulation",
        "appearance",
        "alertness",
        "athletics",
        "brawl",
        "empathy",
        "expression",
        "intimidation",
        "streetwise",
        "subterfuge",
        "awareness",
        "intuition",
        "leadership",
        "seduction",
        "crafts",
        "drive",
        "etiquette",
        "firearms",
        "melee",
        "stealth",
        "performance",
        "security",
        "survival",
        "technology",
        "animal_ken",
        "demolitions",
        "academics",
        "computer",
        "finance",
        "investigation",
        "law",
        "enigmas",
        "medicine",
        "occult",
        "politics",
        "religion",
        "research",
        "science",
        "specialties",
        "languages",
        "willpower",
        "derangements",
        "age",
        "apparent_age",
        "date_of_birth",
        "merits_and_flaws",
        "history",
        "goals",
        "notes",
        "house",
        "faction",
        "visage",
        "faith",
        "temporary_faith",
        "torment",
        "temporary_torment",
        "conviction",
        "courage",
        "conscience",
        "apocalyptic_form",
        "host_name",
        "days_until_consumption",
        "celestial_name",
        "true_name",
        "age_of_fall",
        "abyss_duration",
    ]
    template_name = "characters/demon/demon/form.html"
    success_message = "Demon '{name}' created successfully!"
    error_message = "Failed to create demon. Please correct the errors below."


class DemonUpdateView(ApprovedUserContextMixin, EditPermissionMixin, UpdateView):
    model = Demon
    fields = [
        "name",
        "description",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "perception",
        "intelligence",
        "wits",
        "charisma",
        "manipulation",
        "appearance",
        "alertness",
        "athletics",
        "brawl",
        "empathy",
        "expression",
        "intimidation",
        "streetwise",
        "subterfuge",
        "awareness",
        "intuition",
        "leadership",
        "seduction",
        "crafts",
        "drive",
        "etiquette",
        "firearms",
        "melee",
        "stealth",
        "performance",
        "security",
        "survival",
        "technology",
        "animal_ken",
        "demolitions",
        "academics",
        "computer",
        "finance",
        "investigation",
        "law",
        "enigmas",
        "medicine",
        "occult",
        "politics",
        "religion",
        "research",
        "science",
        "specialties",
        "languages",
        "willpower",
        "derangements",
        "age",
        "apparent_age",
        "date_of_birth",
        "merits_and_flaws",
        "history",
        "goals",
        "notes",
        "house",
        "faction",
        "visage",
        "faith",
        "temporary_faith",
        "torment",
        "temporary_torment",
        "conviction",
        "courage",
        "conscience",
        "apocalyptic_form",
        "host_name",
        "days_until_consumption",
        "celestial_name",
        "true_name",
        "age_of_fall",
        "abyss_duration",
    ]
    template_name = "characters/demon/demon/form.html"
    success_message = "Demon '{name}' updated successfully!"
    error_message = "Failed to update demon. Please correct the errors below."

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
