from characters.models.demon import Thrall
from core.mixins import (
    ApprovedUserContextMixin,
    EditPermissionMixin,
    MessageMixin,
    SpendFreebiesPermissionMixin,
    SpendXPPermissionMixin,
    ViewPermissionMixin,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DetailView, UpdateView


class ThrallDetailView(ApprovedUserContextMixin, ViewPermissionMixin, DetailView):
    model = Thrall
    template_name = "characters/demon/thrall/detail.html"


class ThrallCreateView(MessageMixin, CreateView):
    model = Thrall
    success_message = "Thrall created successfully."
    error_message = "Error creating thrall."
    fields = [
        "name",
        "description",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "perception",
        "intelligence",
        "wits",
        "charisma",
        "manipulation",
        "appearance",
        "alertness",
        "athletics",
        "brawl",
        "empathy",
        "expression",
        "intimidation",
        "streetwise",
        "subterfuge",
        "awareness",
        "intuition",
        "leadership",
        "seduction",
        "crafts",
        "drive",
        "etiquette",
        "firearms",
        "melee",
        "stealth",
        "performance",
        "security",
        "survival",
        "technology",
        "animal_ken",
        "demolitions",
        "academics",
        "computer",
        "finance",
        "investigation",
        "law",
        "enigmas",
        "medicine",
        "occult",
        "politics",
        "religion",
        "research",
        "science",
        "specialties",
        "languages",
        "willpower",
        "derangements",
        "age",
        "apparent_age",
        "date_of_birth",
        "merits_and_flaws",
        "history",
        "goals",
        "notes",
        "faith_potential",
        "daily_faith_offered",
        "master",
        "enhancements",
        "conviction",
        "courage",
        "conscience",
    ]
    template_name = "characters/demon/thrall/form.html"


class ThrallUpdateView(ApprovedUserContextMixin, EditPermissionMixin, UpdateView):
    model = Thrall
    success_message = "Thrall updated successfully."
    error_message = "Error updating thrall."
    fields = [
        "name",
        "description",
        "concept",
        "nature",
        "demeanor",
        "strength",
        "dexterity",
        "stamina",
        "perception",
        "intelligence",
        "wits",
        "charisma",
        "manipulation",
        "appearance",
        "alertness",
        "athletics",
        "brawl",
        "empathy",
        "expression",
        "intimidation",
        "streetwise",
        "subterfuge",
        "awareness",
        "intuition",
        "leadership",
        "seduction",
        "crafts",
        "drive",
        "etiquette",
        "firearms",
        "melee",
        "stealth",
        "performance",
        "security",
        "survival",
        "technology",
        "animal_ken",
        "demolitions",
        "academics",
        "computer",
        "finance",
        "investigation",
        "law",
        "enigmas",
        "medicine",
        "occult",
        "politics",
        "religion",
        "research",
        "science",
        "specialties",
        "languages",
        "willpower",
        "derangements",
        "age",
        "apparent_age",
        "date_of_birth",
        "merits_and_flaws",
        "history",
        "goals",
        "notes",
        "faith_potential",
        "daily_faith_offered",
        "master",
        "enhancements",
        "conviction",
        "courage",
        "conscience",
    ]
    template_name = "characters/demon/thrall/form.html"
