from characters import views
from django.urls import path

app_name = "vampire:detail"
urls = [
    path(
        "vampire/<pk>/",
        views.vampire.VampireDetailView.as_view(),
        name="vampire",
    ),
    path(
        "ghoul/<pk>/",
        views.vampire.GhoulDetailView.as_view(),
        name="ghoul",
    ),
    path(
        "revenant/<pk>/",
        views.vampire.RevenantDetailView.as_view(),
        name="revenant",
    ),
    path(
        "clan/<pk>/",
        views.vampire.VampireClanDetailView.as_view(),
        name="clan",
    ),
    path(
        "sect/<pk>/",
        views.vampire.VampireSectDetailView.as_view(),
        name="sect",
    ),
    path(
        "path/<pk>/",
        views.vampire.PathDetailView.as_view(),
        name="path",
    ),
    path(
        "title/<pk>/",
        views.vampire.VampireTitleDetailView.as_view(),
        name="title",
    ),
    path(
        "discipline/<pk>/",
        views.vampire.DisciplineDetailView.as_view(),
        name="discipline",
    ),
    # Staged character creation routes
    path(
        "vampire/<int:pk>/chargen/",
        views.vampire.VampireCharacterCreationView.as_view(),
        name="vampire_chargen",
    ),
    path(
        "ghoul/<int:pk>/chargen/",
        views.vampire.GhoulCharacterCreationView.as_view(),
        name="ghoul_chargen",
    ),
    path(
        "vtmhuman/<int:pk>/template/",
        views.vampire.VtMHumanTemplateSelectView.as_view(),
        name="vtmhuman_template",
    ),
    path(
        "vtmhuman/<int:pk>/creation/",
        views.vampire.VtMHumanCharacterCreationView.as_view(),
        name="vtmhuman_creation",
    ),
    path(
        "coterie/<pk>/",
        views.vampire.CoterieDetailView.as_view(),
        name="coterie",
    ),
    path(
        "revenant_family/<pk>/",
        views.vampire.RevenantFamilyDetailView.as_view(),
        name="revenant_family",
    ),
]
